import Disaster from './Disaster.js'
import Election from './Election.js'
import MilitaryConflict from './MilitaryConflict.js'
import SportsEvent from './SportsEvent.js'

export default {
  name: 'Event',
  properties: {
    dates: () => { },
    places: () => { },
  },
  children: {
    Disaster,
    Election,
    MilitaryConflict,
    SportsEvent,
  },
  //
  categories: {
    mapping: [
      'years in literature',
      'years in music',
      'years in film',
      'united states supreme court cases',
      'leap years in the gregorian calendar',
      "governor general's awards",
      'eurovision song contest by year',
      'grammy awards ceremonies',
      'united kingdom in the eurovision song contest',
      'manned soyuz missions',
      'american civil liberties union litigation',
      'may',
      'october',
      'missions to the moon',
      'world war ii british commando raids',
      'july',
      'december',
      'september',
      'november',
      'january',
      'june',
      'august',
      'april',
      'february',
      'march',
      'conflicts in 1944',
      'missions to mars',
      'luna program',
      'conflicts in 1942',
      'special air service',
      'soft landings on the moon',
      'may observances',
      'first events',
      'recent years',
      'elections not won by the popular vote winner',
      'conflicts in 1864',
      '1862 in the american civil war',
      'new york (state) in the american revolution',
      'march observances',
      'public holidays in the united states',
      '1944 in france',
      'december observances',
      '20th century american trials',
      'african-american civil rights movement (1954–68)',
      'october observances',
      'spring holidays',
      'years in aviation',
      'national days',
      'summer holidays',
      'apollo program',
    ],
    patterns: [/^(19|20)[0-9]{2} in /, /^(years of the )?[0-9]{1,2}(st|nd|rd|th)? century in ./],
  },
  //
  descriptions: {
    patterns: [],
  },
  //
  infoboxes: {
    mapping: [
      'beauty_pageant',
      'civil_conflict',
      'concert_tour',
      'court_case',
      'event',
      'historical_era',
      'holiday',
      'horseraces',
      'individual_snooker_tournament',
      'legislative_term',
      'music_festival',
      'nfl_draft',
      'pba_draft',
      'reality_music_competition',
      'recurring_event',
      'song_contest',
      'summit',
      'grand prix race report',
      'recurring event',
      'music festival',
      'football league season',
      'scotus case',
      'court case',
      'concert tour',
      'international labour organization convention',
      'song contest',
      'australian year',
      'individual darts tournament',
      'beauty pageant',
      'historical event',
      'grand prix motorcycle race report',
      'international handball competition',
      'coa case',
      'individual snooker tournament',
      'esc national year',
      'indy500',
      'national political convention',
      'referendum',
    ],
    patterns: [],
  },
  //
  sections: {
    mapping: [
      'aftermath',
      'births',
      'deaths',
      'battle',
      'results',
      'prelude',
      'may',
      'june',
      'march',
      'december',
      'october',
      'july',
      'august',
      'april',
      'november',
      'february',
      'september',
      'january',
      'incumbents',
      'casualties',
      'july to december',
      'january to june',
      'medal table',
      'campaign',
    ],
    patterns: [],
  },
  //
  templates: {
    mapping: [
      'esc',
      'year nav',
      'year dab',
      'goal',
      'flagiocmedalist',
      'm1 year in topic',
      'year nav topic5',
      'bc year in topic',
      'flagiocathlete',
      'year article header',
    ],
    patterns: [],
  },
  //
  titles: {
    mapping: ['festival', '25 m', 'world war ii', 'conmebol', 'music festival', 'world war i'],
    patterns: [/ \((19|20)[0-9]{2}\)$/],
  },
}
