import Athlete from './Athlete/index.js'
import Politician from './Politician.js'
import Creator from './Creator/index.js'

export default {
  name: 'Person',
  children: {
    Athlete,
    Creator,
    Politician,
  },
  //
  categories: {
    mapping: [
      'living people',
      'possibly living people',
      'year of birth unknown',
      'fellows of the royal society',
      'members of the privy council of the united kingdom',
      'american people of english descent',
      'guggenheim fellows',
      'harvard university alumni',
      'american military personnel of world war ii',
      'knights bachelor',
      'american roman catholics',
      'knights of the garter',
      'presidential medal of freedom recipients',
      'commanders of the order of the british empire',
      'people educated at eton college',
      'alumni of trinity college, cambridge',
      'foreign members of the royal society',
      'american people of scottish descent',
      'american memoirists',
      'members of the french academy of sciences',
      'united states army soldiers',
      'officers of the order of the british empire',
      'deaths from pneumonia',
      'burials at père lachaise cemetery',
      'deaths from cancer in california',
      'year of birth missing (living people)',
      'knights of the golden fleece',
      'columbia university alumni',
      'alumni of the university of edinburgh',
      'american people of russian-jewish descent',
      'yale university alumni',
      'american atheists',
      'people of the tudor period',
      'tony award winners',
      'members of the académie française',
      'united states army officers',
      'persons of national historic significance (canada)',
      '20th-century american businesspeople',
      'american television producers',
      'american journalists',
      'american male journalists',
      'american male comedians',
      'princeton university alumni',
      'university of paris alumni',
      'american episcopalians',
      'american women novelists',
      'phi beta kappa members',
      '20th-century american poets',
      'bafta winners (people)',
      "members of the queen's privy council for canada",
      'american presbyterians',
      'fellows of the american academy of arts and sciences',
      'members of the united states national academy of sciences',
      'members of the royal swedish academy of sciences',
      '20th-century american short story writers',
      'american nobel laureates',
      'harvard university faculty',
      'roman catholic monarchs',
      'popes',
      'italian popes',
      // redirects to infobox person
      'biography',
      'adult female',
      'adult male',
      'celebrity',
      'biography',
      'actor',
      'actor voice',
      'journalist',
      'actress',
      'performer',
      'fashion designer',
      'adult biography',
      'actress',
      'fashion designer',
      'actor',
      'person',
      'director',
      'film actor',
      'photographer',
      'film director',
      'indian businessmen',
      'victim',
      'trade unionist',
      'journalist',
      'people',
      'personbox',
      'entertainer',
      'person ii',
      'bio',
      'real person',
      'human',
      'human being',
      'person/measurements',
      'student',
      'student',
      'personality',
      'architect',
      'astronaut',
      'chef',
      'clergy',
      'criminal',
      'dancer',
      'engineer',
      'aviator',
      'medical person',
      'model',
      'pageant titleholder',
      'pirate',
      'police officer',
      'presenter',
      'professional bowler',
      'scientist',
      'sports announcer',
      'spy',
    ],
    patterns: [
      /[0-9]{4} births/,
      /[0-9]{4} deaths/,
      /people of .* descent/,
      /^deaths from /,
      /^(people|philanthropists|writers) from ./,
      / (players|alumni)$/,
      /(alumni|fellows) of .$/,
      /(people|writer) stubs$/,
      /(american|english) (fe)?male ./,
      /(american|english) (architects|people)/,
    ],
  },
  //
  descriptions: {
    patterns: [/(artist|painter|poet|writer|celebrity|activist)/],
  },
  //
  infoboxes: {
    mapping: [

      'adult_biography',
      'archbishop',
      'architect',
      'artist',
      'astronaut',
      'bishop',
      'chef',
      'chess_player',
      'chinese-language_singer_and_actor',
      'christian_leader',
      'coa_wide',
      'college_coach',
      'college_football_player',
      'comedian',
      'comics_creator',
      'criminal',
      'economist',
      'engineer',
      'f1_driver',
      'fashion_designer',
      'football_biography',
      'gridiron_football_person',
      'handball_biography',
      'hindu_leader',
      'horseracing_personality',
      'judge',
      'martial_artist',
      'mass_murderer',
      'medical_person',
      'military_person',
      'minister',
      'model',
      'monarch',
      'nascar_driver',
      'pageant_titleholder',
      'person',
      'philosopher',
      'police_officer',
      'presenter',
      'racing_driver',
      'religious_biography',
      'royalty',
      'saint',
      'scholar',
      'scientist',
      'snooker_player',
      'sportsperson',
      'wrc_driver',
      'writer',
    ],
    patterns: [],
  },
  //
  sections: {
    mapping: [
      'early life',
      'personal life',
      'career',
      'career statistics',
      'playing career',
      'life and career',
      'early life and education',
      'film and television credits',
      'filmography',
      'selected filmography',
      'works',
      'life',
      'family',
      'political career',
      'early career',
      'later life',
      'early life and career',
      'later years',
      'death and legacy',
      'work',
      'novels',
      'later career',
      'international',
      'selected works',
      'writings',
      'professional career',
      'retirement',
      'poetry',
      'marriage',
      'electoral history',
      'military career',
      'international career',
      'parliamentary career',
    ],
    patterns: [],
  },
  //
  templates: {
    mapping: [
      'persondata',
      'writer',
      'ted speaker',
      's-aft',
      's-bef',
      's-start',
      'marriage',
      's-off',
      's-par',
      'internet archive author',
      'ribbon devices',
      's-reg',
      'find a grave',
      'gutenberg author',
      's-new',
      'other people',
      'medalgold',
      'medal',
      'mlby',
      's-vac',
      's-hou',
      'librivox author',
      'blp sources',
      's-ppo',
      'nbay',
    ],
    patterns: [/-bio-stub$/],
  },
  //
  titles: {
    mapping: [
      'murder victim',
      'academic',
      'author',
      'businessman',
      'cyclist',
      'diplomat',
      'director',
      'drummer',
      'journalist',
      'judge',
      'minister',
      'poet',
      'priest',
      'american football',
      'ice hockey',
      'soccer',
      'rugby league',
      'rugby union',
      'field hockey',
      'tennis',
      'writer',
      'vc',
      'racing driver',
      'architect',
      'comedian',
      'british army officer',
      'general',
      'broadcaster',
      'engineer',
      'physician',
      'soldier',
      'royal navy officer',
      'producer',
      'lawyer',
      'activist',
      'inventor',

      'artist',
      'painter',
      'cartoonist',
      'novelist',
      'photographer',
      'playwright',
      'bishop',
      'theologian',
      'historian',
      'philosopher',
      'mathematician',
      'astronomer',
      'economist',
    ],
    patterns: [],
  },
}
