module.exports = {
  id: 'Person',
  children: {
    Athlete: require('./Athlete'),
    Actor: require('./Actor'),
    Politician: require('./Politician'),
    Musician: require('./Musician'),
    Author: require('./Author'),
  },
  properties: {
    birth_date: () => {},
    birth_place: () => {},
    nationality: () => {},
    death_date: () => {},
    death_place: () => {},
  },
  //
  categories: {
    mapping: [
      'living people',
      'possibly living people',
      'year of birth unknown',
      'fellows of the royal society',
      'members of the privy council of the united kingdom',
      'american people of english descent',
      'guggenheim fellows',
      'harvard university alumni',
      'american military personnel of world war ii',
      'knights bachelor',
      'american roman catholics',
      'knights of the garter',
      'presidential medal of freedom recipients',
      'commanders of the order of the british empire',
      'people educated at eton college',
      'alumni of trinity college, cambridge',
      'foreign members of the royal society',
      'american people of scottish descent',
      'american memoirists',
      'members of the french academy of sciences',
      'united states army soldiers',
      'officers of the order of the british empire',
      'deaths from pneumonia',
      'burials at père lachaise cemetery',
      'deaths from cancer in california',
      'year of birth missing (living people)',
      'knights of the golden fleece',
      'columbia university alumni',
      'alumni of the university of edinburgh',
      'american people of russian-jewish descent',
      'yale university alumni',
      'american atheists',
      'people of the tudor period',
      'tony award winners',
      'members of the académie française',
      'united states army officers',
      'persons of national historic significance (canada)',
      '20th-century american businesspeople',
      'american television producers',
      'american journalists',
      'american male journalists',
      'american male comedians',
      'princeton university alumni',
      'university of paris alumni',
      'american episcopalians',
      'american women novelists',
      'phi beta kappa members',
      '20th-century american poets',
      'bafta winners (people)',
      "members of the queen's privy council for canada",
      'american presbyterians',
      'fellows of the american academy of arts and sciences',
      'members of the united states national academy of sciences',
      'members of the royal swedish academy of sciences',
      '20th-century american short story writers',
      'american nobel laureates',
      'harvard university faculty',
      'roman catholic monarchs',
      'popes',
      'italian popes',
    ],
    patterns: [
      /[0-9]{4} births/,
      /[0-9]{4} deaths/,
      /people of .* descent/,
      /^deaths from /,
      /^(people|philanthropists|writers) from ./,
      / (players|alumni)$/,
      /(alumni|fellows) of .$/,
      /(people|writer) stubs$/,
      /(american|english) (fe)?male ./,
      /(american|english) (architects|people)/,
    ],
  },
  //
  descriptions: {
    patterns: [],
  },
  //
  infoboxes: {
    mapping: [],
    patterns: [],
  },
  //
  sections: {
    mapping: [],
    patterns: [],
  },
  //
  templates: {
    mapping: [],
    patterns: [],
  },
  //
  titles: {
    mapping: [],
    patterns: [],
  },
}
