export default {
  name: 'Musician',
  //
  children: {},
  properties: {
    groups: () => { },
    instruments: () => { },
  },
  //
  categories: {
    mapping: [
      'american male guitarists',
      'american singer-songwriters',
      'american male singers',
      'american rock singers',
      'american rock guitarists',
      '21st-century american singers',
      'lead guitarists',
      'african-american musicians',
      'english male singers',
      'american male singer-songwriters',
      'american rock songwriters',
      'american record producers',
      'american country singer-songwriters',
      '20th-century american guitarists',
      'english songwriters',
      '20th-century american pianists',
      'songwriters from new york (state)',
      'african-american singers',
      'american blues singers',
      'american pop singers',
      'male guitarists',
      'american country singers',
      'blues hall of fame inductees',
      'american male songwriters',
      'songwriters from california',
      'english rock guitarists',
      'american folk singers',
      'english rock singers',
      'english singer-songwriters',
      'african-american male rappers',
      'african-american jazz musicians',
      '20th-century english singers',
      'american female singer-songwriters',
      'jewish american musicians',
      'american blues guitarists',
      '20th-century conductors (music)',
      'american female singers',
      'american jazz bandleaders',
      'american jazz pianists',
      'american soul singers',
      'american female guitarists',
      'american multi-instrumentalists',
      'american country guitarists',
      'english record producers',
      'songwriters from texas',
      'american composers',
      'singers from california',
      'american folk guitarists',
      'lgbt singers',
      'american buskers',
      'guitarists from california',
      'feminist musicians',
      'big band bandleaders',
      '20th-century composers',
      'african-american songwriters',
      'british rhythm and blues boom musicians',
      'alternative rock singers',
      '21st-century american guitarists',
      'american alternative rock musicians',
      'musicians from los angeles',
      'rhythm guitarists',
      'american session musicians',
      'jazz musicians from new orleans',
      'alternative rock guitarists',
      '20th-century women musicians',
      'male film score composers',
      'african-american singer-songwriters',
      'american jazz singers',
      '21st-century english singers',
      'singers from new york city',
      'american acoustic guitarists',
      'musicians from new york city',
      'slide guitarists',
      'guitarists from texas',
      'vaudeville performers',
    ],
    patterns: [/musicians from ./, /(singers|songwriters|painters|poets)/],
  },
  //
  descriptions: {
    patterns: [/(singer|musicianrapper|drummer)/, /(keyboard|guitar|bass) player/],
  },
  //
  infoboxes: {
    mapping: [],
    patterns: [],
  },
  //
  sections: {
    mapping: [],
    patterns: [],
  },
  //
  templates: {
    mapping: [],
    patterns: [/(musician|singer)-stub$/],
  },
  //
  titles: {
    mapping: ['composer', 'musician', 'rapper', 'singer'],
    patterns: [],
  },
}
