export default {
  name: 'Politician',
  //
  children: {},
  //
  categories: {
    mapping: [
      'uk mps 2001–05',
      'uk mps 1997–2001',
      'uk mps 2005–10',
      'uk mps 1992–97',
      'labour party (uk) mps for english constituencies',
      'conservative party (uk) mps for english constituencies',
      'uk mps 1987–92',
      'uk mps 2010–15',
      'democratic party members of the united states house of representatives',
      'republican party members of the united states house of representatives',
      'uk mps 1983–87',
      'democratic party state governors of the united states',
      'california republicans',
      'british secretaries of state',
      'democratic party united states senators',
      'uk mps 2015–17',
      'republican party united states senators',
      'republican party state governors of the united states',
      'california democrats',
      'uk mps 1979–83',
      'uk mps 2017–',
    ],
    patterns: [
      /politicians from ./,
      /politician stubs$/,
      /. politicians$/, //democrats|republicans
      /mayors of ./,
    ],
  },
  //
  descriptions: {
    patterns: [/(politician|member of parliament)/],
  },
  //
  infoboxes: {
    // transcluded to officeholder
    mapping: [
      'am',
      'ambassador',
      'canadian_mp',
      'canadian_politician',
      'canadian_senator',
      'canadianmp',
      'canadiansenator',
      'candidate',
      'chairman',
      'chancellor',
      'chief_executive',
      'chief_justice',
      'civil_servant',
      'congressional_candidate',
      'congressman',
      'congressperson',
      'congresswoman',
      'defence_minister',
      'defense_minister',
      'deputy_first_minister',
      'deputy_prime_minister',
      'doge',
      'eritrea_cabinet_official',
      'first_gentleman',
      'first_lady',
      'first_minister',
      'general_secretary',
      'governor_general',
      'governor-elect',
      'governor-general',
      'governor',
      'indian_government_official',
      'indian_politician',
      'league_commissioner',
      'lt_governor',
      'mayor',
      'member_of_parliament',
      'member_of_state_duma',
      'mep',
      'mla',
      'mp',
      'mpp',
      'msp',
      'new_york_state_senator',
      'office_holder',
      'officeholder_infobox',
      'officeholder',
      'ontariompp',
      'people\'s_deputy',
      'pm',
      'politician_(general)',
      'politician_basic',
      'politician_infobox',
      'politician',
      'politicien',
      'premier',
      'president-elect',
      'president',
      'prime_minister-elect',
      'prime_minister',
      'quebecmna',
      'representative_elect',
      'representative-elect',
      'roman_emperor',
      'royalofficeholder',
      'scc_chief_justice',
      'scc_puisne_justice',
      'second_gentleman',
      'second_lady',
      'secretary-general',
      'secretary',
      'senator-elect',
      'senator',
      'speaker',
      'spouse_of_the_president',
      'spouse_of_the_vice_president',
      'state_representative',
      'state_sc_associate_justice',
      'state_sc_justice',
      'state_senator',
      'ukrainian_legislative_office',
      'university_chancellor',
      'university_president',
      'university_pro-chancellor',
      'university_rector',
      'university_vice-chancellor',
      'uruguayan_politician',
      'us_ambassador',
      'us_associate_justice',
      'us_cabinet_official',
      'us_chief_justice',
      'us_territorial_governor',
      'vice_president',
      'vice-president',
      'welsh_assembly_member',
    ],
    patterns: [],
  },
  //
  sections: {
    mapping: [],
    patterns: [],
  },
  //
  templates: {
    mapping: ['list of united states senators congress'],
    patterns: [/(politician|mayor)-stub$/],
  },
  //
  titles: {
    mapping: [
      'australian politician',
      'canadian politician',
      'politician',
      'british politician',
      'governor',
      'irish politician',
      'mayor',
    ],
    patterns: [],
  },
}
