module.exports = {
  // person
  'early life': 'Person',
  'personal life': 'Person',
  career: 'Person',
  'career statistics': 'Person',
  'playing career': 'Person',
  'life and career': 'Person',
  'early life and education': 'Person',
  'film and television credits': 'Person',
  filmography: 'Person',
  'selected filmography': 'Person',
  // place
  demographics: 'Place',
  neighbourhoods: 'Place',
  climate: 'Place',
  'sister cities': 'Place/City',
  'notable people': 'Place',
  // creative-work
  cast: 'CreativeWork/Film',
  plot: 'CreativeWork',
  reception: 'CreativeWork',
  // 'critical reception': 'CreativeWork',
  // 'critical response': 'CreativeWork',
  'track listing': 'CreativeWork/Album',
  // org
  founding: 'Organization',
  founders: 'Organization',
  'coaching staff': 'Organization/SportsTeam',
  'head coaches': 'Organization/SportsTeam',
  'team records': 'Organization/SportsTeam',
  'band members': 'Organization/MusicalGroup',

  habitat: 'Organism',
  morphology: 'Organism',
  phylogeny: 'Organism',
  'distribution and diversity': 'Organism',
  'distribution and habitat': 'Organism',
  'reproduction and development': 'Organism',
  'taxonomy and phylogeny': 'Organism',

  // march 29th
  //learned works
  // production: 'CreativeWork',
  charts: 'CreativeWork',
  release: 'CreativeWork',
  'plot summary': 'CreativeWork',
  gameplay: 'CreativeWork',
  characters: 'CreativeWork',
  'box office': 'CreativeWork',
  accolades: 'CreativeWork',
  soundtrack: 'CreativeWork',
  adaptations: 'CreativeWork',
  synopsis: 'CreativeWork',
  'home media': 'CreativeWork',
  'weekly charts': 'CreativeWork',
  themes: 'CreativeWork',
  'publication history': 'CreativeWork',
  filming: 'CreativeWork',
  'year-end charts': 'CreativeWork',
  casting: 'CreativeWork',
  'release and reception': 'CreativeWork',
  'commercial performance': 'CreativeWork',
  composition: 'CreativeWork',
  album: 'CreativeWork',
  setting: 'CreativeWork',
  'chart positions': 'CreativeWork',
  'release history': 'CreativeWork',
  'charts and certifications': 'CreativeWork',
  sequels: 'CreativeWork',
  'chart performance': 'CreativeWork',
  sequel: 'CreativeWork',
  recordings: 'CreativeWork',
  story: 'CreativeWork',
  editions: 'CreativeWork',
  'in other media': 'CreativeWork',

  // learned events
  aftermath: 'Event',
  births: 'Event',
  deaths: 'Event',
  battle: 'Event',
  results: 'Event',
  prelude: 'Event',
  may: 'Event',
  june: 'Event',
  march: 'Event',
  december: 'Event',
  october: 'Event',
  july: 'Event',
  august: 'Event',
  april: 'Event',
  november: 'Event',
  february: 'Event',
  september: 'Event',
  january: 'Event',
  incumbents: 'Event',
  casualties: 'Event',
  'july to december': 'Event',
  'january to june': 'Event',
  'medal table': 'Event',
  'mission highlights': 'Event/SpaceMission',
  campaign: 'Event',

  // learned orgs
  albums: 'Organization/MusicalGroup',
  'studio albums': 'Organization/MusicalGroup',
  members: 'Organization',
  athletics: 'Organization',
  'notable alumni': 'Organization',
  academics: 'Organization',
  campus: 'Organization',
  organization: 'Organization',
  'student life': 'Organization',
  rankings: 'Organization',
  'compilation albums': 'Organization/MusicalGroup',
  // origins: 'Organization',
  'live albums': 'Organization/MusicalGroup',
  products: 'Organization/Company',
  fleet: 'Organization',
  compilations: 'Organization/MusicalGroup',
  research: 'Organization',
  formation: 'Organization',
  operations: 'Organization',
  'current squad': 'Organization/SportsTeam',
  players: 'Organization',
  alumni: 'Organization',
  eps: 'Organization/MusicalGroup',
  'former members': 'Organization',
  presidents: 'Organization',
  membership: 'Organization',
  'current members': 'Organization',

  // learned people
  works: 'Person',
  life: 'Person',
  family: 'Person',
  'political career': 'Person',
  'early career': 'Person',
  // ancestry: 'Person',
  'later life': 'Person',
  'early life and career': 'Person',
  'later years': 'Person',
  'death and legacy': 'Person',
  work: 'Person',
  novels: 'Person',
  'later career': 'Person',
  international: 'Person',
  'selected works': 'Person',
  writings: 'Person',
  'professional career': 'Person',
  retirement: 'Person',
  poetry: 'Person',
  marriage: 'Person',
  // films: 'Person',
  'electoral history': 'Person',
  'military career': 'Person',
  'international career': 'Person',
  'parliamentary career': 'Person',

  // learned places
  geography: 'Place',
  '2010 census': 'Place',
  '2000 census': 'Place',
  economy: 'Place',
  transportation: 'Place',
  government: 'Place',
  communities: 'Place',
  transport: 'Place',
  culture: 'Place',
  sports: 'Place',
  'adjacent counties': 'Place',
  'major highways': 'Place',
  'notable residents': 'Place',
  tourism: 'Place',
  cities: 'Place',
  population: 'Place',
  'unincorporated communities': 'Place',
  'international relations': 'Place',
  infrastructure: 'Place',
  schools: 'Place',
  rail: 'Place',
  'census-designated places': 'Place',
  towns: 'Place',
  'local government': 'Place',
  'points of interest': 'Place',
  attractions: 'Place',
  geology: 'Place',
  townships: 'Place',
  recreation: 'Place',
  location: 'Place',
  'arts and culture': 'Place',
  governance: 'Place',
  'administrative divisions': 'Place',
  landmarks: 'Place',
  demography: 'Place',
  'parks and recreation': 'Place',
  'public transportation': 'Place',
  'coat of arms': 'Place',
  churches: 'Place'

  // learned things
  //compatibility: 'Thing',
  //compliance: 'Thing',
  //'key features': 'Thing'
}
