export default [
  'Boston Bruins',
  'Buffalo Sabres',
  'Detroit Red Wings',
  'Florida Panthers',
  'Montreal Canadiens',
  'Ottawa Senators',
  'Tampa Bay Lightning',
  'Toronto Maple Leafs',
  'Carolina Hurricanes',
  'Columbus Blue Jackets',
  'New Jersey Devils',
  'New York Islanders',
  'New York Rangers',
  'Philadelphia Flyers',
  'Pittsburgh Penguins',
  'Washington Capitals',
  'Chicago Blackhawks',
  'Colorado Avalanche',
  'Dallas Stars',
  'Minnesota Wild',
  'Nashville Predators',
  'St. Louis Blues',
  'Winnipeg Jets',
  'Anaheim Ducks',
  'Arizona Coyotes',
  'Calgary Flames',
  'Edmonton Oilers',
  'Los Angeles Kings',
  'San Jose Sharks',
  'Vancouver Canucks',
  'Vegas Golden Knights',
]
