//templates we support
const keep = {
  main: true,
  'main article': true,
  'wide image': true,
  coord: true,
  //date/age/time templates
  'birth date': true,
  'death date': true,
  'birth date and age': true,
  'birth date and age2': true,
  'birth date and given age': true,
  'death date and age': true,
  'death date and given age': true,
  'death year and age': true,
  'start date': true,
  'end date': true,
  'start date and age': true,
  birthdeathage: true,
  dob: true,
  bda: true,
  'age': true,
  'age nts': true,
  'age in years, months and days': true,
  'age in years and months': true,
  'age in years and days': true,
  'age in years, months, weeks and days': true,
  'age in days': true,
  'age as of date': true,
};
module.exports = keep;
