export default {
  name: 'Organism',
  //
  children: {},
  //
  categories: {
    mapping: [
      'agamidae',
      'american_inventions',
      'angiosperm_orders',
      'animal_dance',
      'animal_phyla',
      'berries',
      'bird_families',
      'birds_by_common_name',
      'calidris',
      'cimolodonts',
      'commercial_fish',
      'corvus_(genus)',
      'cretaceous_mammals',
      'crops_originating_from_the_americas',
      'crops',
      'ducks',
      'edge_species',
      'edible_nuts_and_seeds',
      'entheogens',
      'epiphytic_orchids',
      'flowers',
      'fruits_originating_in_asia',
      'geckos',
      'geese',
      'herbs',
      'indian_spices',
      'insects_in_culture',
      'invasive_plant_species',
      'leaf_vegetables',
      'living_fossils',
      'mammal_families',
      'marine_edible_fish',
      'megafauna',
      'multituberculates',
      'non-timber_forest_products',
      'ornamental_trees',
      'paleocene_genus_extinctions',
      'paleocene_mammals',
      'phelsuma',
      'pinus',
      'plants_and_pollinators',
      'ptilodontoids',
      'root_vegetables',
      'setophaga',
      'shorebirds',
      'skinks',
      'spices',
      'taxa_named_by_carl_linnaeus',
      'taxa_named_by_john_edward_gray',
      'taxa_named_by_leopold_fitzinger',
      'tropical_agriculture',
      'tropical_fruit',
      'urban_animals',
    ],
    patterns: [
      /(funghi|reptiles|flora|fauna|fish|birds|trees|mammals|plants) of ./,
      / first appearances/,
      / . described in [0-9]{4}/,
      /. (phyla|genera)$/,
      /. taxonomic families$/,
      /plants used in ./,
      / (funghi|reptiles|flora|fauna|fish|birds|trees|mammals|plants)$/,
    ],
  },
  //
  descriptions: {
    patterns: [],
  },
  //
  infoboxes: {
    mapping: [
      'speciesbox',
      'automatic_taxobox',
      'dogbreed',
      'dog_breed',
      'cat_breed',
      'grape_variety',
      'taxobox',
      'subspeciesbox',
      'mycomorphbox',
      'paraphyletic_group',
      'nutritional_value',
      'infraspeciesbox',
      'horse',
      'haplogroup',
      'bird',
      'bird/population',
      'medical_resources',
      'nc_name',
      'pig_breed',
      'botanical_product',
      'cattle_breed',
      'horse_breed',
      'poultry_breed',
    ],
    patterns: [],
  },
  //
  sections: {
    mapping: [
      'habitat',
      'morphology',
      'phylogeny',
      'distribution and diversity',
      'distribution and habitat',
      'reproduction and development',
      'taxonomy and phylogeny',
    ],
    patterns: [],
  },
  //
  templates: {
    mapping: [
      'taxonbar',
      'wikispecies',
      'animalia',
      'chordata',
      'cnidaria',
      'porifera',
      'epicaridea',
      'mammals',
      'phlyctaeniidae',
      'carnivora',
      'clade',
      'life on earth',
      'orders of insects',
      'coleoptera',
      'insects in culture',
      'living things in culture',
      'eukaryota classification',
      'iucn status',
      'extinct',
      'fossil range',
      'internetbirdcollection',
      'vireo',
      'angle bracket',
      'wikispecies-inline',
      'iucn map',
      'xeno-canto species',
      'avibase',
      'cladex',
      'birdlife',
      'fossilrange',
    ],
    patterns: [],
  },
  //
  titles: {
    mapping: ['plant', 'genus', 'fish', 'bird'],
    patterns: [],
  },
}
