module.exports = {
  //place
  coord: 'Place',
  'weather box': 'Place',

  //person
  persondata: 'Person',
  writer: 'Person',
  'ted speaker': 'Person',
  taxonbar: 'Organism',
  wikispecies: 'Organism',
  animalia: 'Organism',
  chordata: 'Organism',
  cnidaria: 'Organism',
  porifera: 'Organism',
  epicaridea: 'Organism',
  mammals: 'Organism',
  phlyctaeniidae: 'Organism',
  carnivora: 'Organism',
  clade: 'Organism',
  'life on earth': 'Organism',
  'orders of insects': 'Organism',
  coleoptera: 'Organism',
  'insects in culture': 'Organism',
  'living things in culture': 'Organism',
  'eukaryota classification': 'Organism',

  // creative work
  rating: 'CreativeWork',
  'certification table entry': 'CreativeWork',
  'imdb title': 'CreativeWork/Film',
  'track listing': 'CreativeWork/Album',
  albumchart: 'CreativeWork',
  'film date': 'CreativeWork/Film',
  music: 'CreativeWork',
  // vgrelease: 'CreativeWork',
  // chem: 'CreativeWork',
  'album ratings': 'CreativeWork',
  tracklist: 'CreativeWork/Album',
  'episode list': 'CreativeWork/TVShow',
  'album chart': 'CreativeWork',
  'rotten-tomatoes': 'CreativeWork/Film',
  singles: 'CreativeWork',
  isbnt: 'CreativeWork',
  singlechart: 'CreativeWork',
  'tcmdb title': 'CreativeWork',
  'mojo title': 'CreativeWork',
  'based on': 'CreativeWork',
  'amg movie': 'CreativeWork',
  duration: 'CreativeWork',

  // learned events
  esc: 'Event',
  'year nav': 'Event',
  'year dab': 'Event',
  goal: 'Event',
  flagiocmedalist: 'Event',
  'm1 year in topic': 'Event',
  'year nav topic5': 'Event',
  'bc year in topic': 'Event',
  flagiocathlete: 'Event',
  'election summary party with leaders': 'Event/Election',
  'year article header': 'Event',

  //learned organisms
  'iucn status': 'Organism',
  extinct: 'Organism',
  'fossil range': 'Organism',
  internetbirdcollection: 'Organism',
  vireo: 'Organism',
  'angle bracket': 'Organism',
  'wikispecies-inline': 'Organism',
  'iucn map': 'Organism',
  'xeno-canto species': 'Organism',
  avibase: 'Organism',
  cladex: 'Organism',
  birdlife: 'Organism',
  fossilrange: 'Organism',

  //leaned orgs
  'composition bar': 'Organization',
  'fs player': 'Organization',
  y: 'Organization',
  n: 'Organization',
  rws: 'Organization',
  allmusic: 'Organization/MusicalGroup',

  // learned people
  's-aft': 'Person',
  's-bef': 'Person',
  's-start': 'Person',
  marriage: 'Person',
  'list of united states senators congress': 'Person/Politician',
  's-off': 'Person',
  's-par': 'Person',
  'internet archive author': 'Person',
  'ribbon devices': 'Person',
  's-reg': 'Person',
  'find a grave': 'Person',
  'gutenberg author': 'Person',
  's-new': 'Person',
  'other people': 'Person',
  medalgold: 'Person',
  'baseball year': 'Person/Athlete',
  medal: 'Person',
  // 'post-nominals': 'Person',
  mlby: 'Person',
  's-vac': 'Person',
  's-hou': 'Person',
  'librivox author': 'Person',
  'blp sources': 'Person',
  's-ppo': 'Person',
  nbay: 'Person',

  //learned places
  'us census population': 'Place',
  jct: 'Place',
  'geographic location': 'Place',
  // wikivoyage: 'Place',
  representative: 'Place',
  'historical populations': 'Place',
  'wikivoyage-inline': 'Place',
  'election box': 'Place',
  zh: 'Place',
  'wide image': 'Place'
}
