module.exports = {
  'bdsm in films': 'Sexuality',
  sexuality: 'Sexuality',

  // https://en.wikipedia.org/wiki/Category:Sexuality
  'sexuality by culture': 'Sexuality',
  'human sexuality': 'Sexuality',
  'animal sexuality': 'Sexuality',
  'plant sexuality': 'Sexuality',
  'historians of sexuality': 'Sexuality',
  mating: 'Sexuality',
  promiscuity: 'Sexuality',
  'sexual reproduction': 'Sexuality',
  'sexual acts': 'Sexuality',
  'sexuality by region': 'Sexuality',
  'sexuality stubs': 'Sexuality',
  'casual sex': 'Sexuality',
  'group sex': 'Sexuality',
  prostitution: 'Sexuality',
  'casual sex in fiction': 'Sexuality',
  'free sex': 'Sexuality',
  'gay bathhouses': 'Sexuality',
  'sex positivism': 'Sexuality',
  'sexual addiction': 'Sexuality',
  'sexual revolution': 'Sexuality',
  'songs about casual sex': 'Sexuality',
  'swinging (sexual practice)': 'Sexuality',
  'free sex activists': 'Sexuality',
  bukkake: 'Sexuality',
  'sex gangs': 'Sexuality',
  'child prostitution': 'Sexuality',
  'corrective rape': 'Sexuality',
  'forced prostitution': 'Sexuality',
  'sexual slavery': 'Sexuality',
  'wartime sexual violence': 'Sexuality',
  'wartime sexual violence in world war ii': 'Sexuality',
  'abu ghraib torture and prisoner abuse': 'Sexuality',
  '1980 murders of u.s. missionaries in el salvador': 'Sexuality',
  'genocidal rape': 'Sexuality',
  'comfort gays': 'Sexuality',
  'comfort women': 'Sexuality',
  'nanjing massacre': 'Sexuality',
  'forced prostitution in the united states': 'Sexuality',
  'victims of forced prostitution': 'Sexuality',
  brothels: 'Sexuality',
  'magdalene asylums': 'Sexuality',
  pimps: 'Sexuality',
  prostitutes: 'Sexuality',
  'prostitution by gender': 'Sexuality',
  'red-light districts': 'Sexuality',
  'sex industry researchers': 'Sexuality',
  "sex workers' rights": 'Sexuality',
  'works about prostitution': 'Sexuality',
  'american pimps': 'Sexuality',
  'argentine pimps': 'Sexuality',
  'british pimps': 'Sexuality',
  'cuban pimps': 'Sexuality',
  'french pimps': 'Sexuality',
  'german pimps': 'Sexuality',
  'mexican pimps': 'Sexuality',
  'south african pimps': 'Sexuality',
  'spanish pimps': 'Sexuality',
  'swedish pimps': 'Sexuality',
  'brothel owners and madams': 'Sexuality',
  'prostitutes by nationality': 'Sexuality',
  'prostitutes by type': 'Sexuality',
  'cultural depictions of prostitutes': 'Sexuality',
  'fictional prostitutes': 'Sexuality',
  'prostitutes by gender': 'Sexuality',
  'songs about prostitutes': 'Sexuality',
  'female prostitutes by nationality': 'Sexuality',
  'male prostitutes by nationality': 'Sexuality',
  'dominatrices by nationality': 'Sexuality',
  'erotic dancers by nationality': 'Sexuality',
  'pornographic film actors by nationality': 'Sexuality',

  //
  axes: 'Weapons',
  bayonets: 'Weapons',
  daggers: 'Weapons',
  'deaths by blade weapons': 'Weapons',
  guillotine: 'Weapons',
  knives: 'Weapons',
  'medieval blade weapons': 'Weapons',
  'military knives': 'Weapons',
  'single-edged swords': 'Weapons',
  spears: 'Weapons',
  swords: 'Weapons',
  'lists of swords': 'Weapons',
  'swords by region': 'Weapons',
  'coats of arms with swords': 'Weapons',
  'fictional swords': 'Weapons',
  'mythological swords': 'Weapons',
  'sword swallowers': 'Weapons',
  'swords by period': 'Weapons',
  swordsmanship: 'Weapons',
  swordsmiths: 'Weapons',

  alcohol: 'Drug-use',
  amphetamine: 'Drug-use',
  ayahuasca: 'Drug-use',
  cannabis: 'Drug-use',
  coca: 'Drug-use',
  cocaine: 'Drug-use',
  ghb: 'Drug-use',
  heroin: 'Drug-use',
  iboga: 'Drug-use',
  'lysergic acid diethylamide': 'Drug-use',
  methamphetamine: 'Drug-use',
  methylphenidate: 'Drug-use',
  morphine: 'Drug-use',
  opium: 'Drug-use',
  tobacco: 'Drug-use',
  'psychedelics, dissociatives and deliriants': 'Drug-use',
  'works about drugs': 'Drug-use',
  'biological sources of psychoactive drugs': 'Drug-use',
  'chemical classes of psychoactive drugs': 'Drug-use',
  'combinations of psychoactive drugs': 'Drug-use',
  'designer drugs': 'Drug-use',
  'drug classes defined by psychological effects': 'Drug-use',
  'drugs and the military': 'Drug-use',
  'drugs by psychological effects': 'Drug-use',
  'effects of psychoactive drugs': 'Drug-use',
  'individual psychoactive drugs': 'Drug-use',
  inhalants: 'Drug-use',
  'psychoactive drugs by mechanism of action': 'Drug-use',
  'psychedelic drug research': 'Drug-use',
  'social aspects of psychoactive drugs': 'Drug-use',
  'psychoactive drug stubs': 'Drug-use'
}
