import MusicalGroup from './MusicalGroup.js'
import Company from './Company.js'
import SportsTeam from './SportsTeam.js'
import PoliticalParty from './PoliticalParty.js'
import School from './School.js'

export default {
  name: 'Organization',
  //
  children: {
    MusicalGroup,
    Company,
    SportsTeam,
    PoliticalParty,
    School
  },
  //
  categories: {
    mapping: [
      'japanese brands',
      'american jazz composers',
      'scouting in the united states',
      'car brands',
      'government-owned airlines',
      'baptist denominations in north america',
      'baptist denominations established in the 20th century',
      'video game publishers',
      'defunct motor vehicle manufacturers of the united states',
      'alternative rock groups from california',
    ],
    patterns: [
      /(organi[sz]ations|publications) based in /,
      /(organi[sz]ations|publications|awards) established in [0-9]{4}/,
      /military units/,
      /magazines/,
      /organi[sz]ation stubs$/,
    ],
  },
  //
  descriptions: {
    patterns: [/(charity|organization|ngo)/],
  },
  //
  infoboxes: {
    mapping: [

      'airline',
      'athletic_conference',
      'brewery',
      'broadcasting_network',
      'bus_transit',
      'caste',
      'cbb_team',
      'choir',
      'christian_denomination',
      'clan',
      'court',
      'criminal_organization',
      'detention_facility',
      'diocese',
      'dot-com_company',
      'ethnic_group',
      'family',
      'fictional_organisation',
      'film_awards',
      'film_festival',
      'fire_department',
      'football_league',
      'former_monarchy',
      'fraternity',
      'gaa_club',
      'government_agency',
      'government_cabinet',
      'government',
      'grand_lodge',
      'hereditary_title',
      'india_university_ranking',
      'institute',
      'iwi',
      'journal',
      'laboratory',
      'law_enforcement_agency',
      'legislature',
      'library',
      // 'magazine',
      'military_gear',
      'military_rank',
      'military_unit',
      'monarchy',
      'monastery',
      'museum',
      'national_military',
      'ncaa_football_school',
      'newspaper',
      'nobility',
      'observatory',
      'order',
      'organization',
      'public_transit',
      'publisher',
      'radio_station',
      'rail_line',
      'rail_service',
      'rail',
      'religious_group',
      'school_district',
      'sg_rail',
      'space_agency',
      'sport_governing_body',
      'sports_league',
      'tribe',
      'tv_channel',
      'u.s._cabinet',
      'u.s._legislation',
      'uk_legislation',
      'uk_university_rankings',
      'union',
      'us_university_ranking',
      'v8_supercar_team',
      'website',
      'worldscouting',
    ],
    patterns: [],
  },
  //
  sections: {
    mapping: [
      'founding',
      'founders',
      'members',
      'athletics',
      'notable alumni',
      'academics',
      'campus',
      'organization',
      'student life',
      'rankings',
      'fleet',
      'research',
      'formation',
      'operations',
      'players',
      'alumni',
      'former members',
      'presidents',
      'membership',
      'current members',
    ],
    patterns: [],
  },
  //
  templates: {
    mapping: ['composition bar', 'fs player', 'y', 'n', 'rws'],
    patterns: [],
  },
  //
  titles: {
    mapping: [
      'group',
      'journal',
      'am',
      'fm',
      'wehrmacht',
      'tv channel',
      'british band',
      'organization',
      'airline',
      'publisher',
      'brand',
      'record label',
      'union army',
      'defunct',
      'tv network',
      'department store',
    ],
    patterns: [],
  },
}
