module.exports = {
  name: 'Organization',
  //
  children: {
    MusicalGroup: require('./MusicalGroup'),
    Company: require('./Company'),
    SportsTeam: require('./SportsTeam'),
    PoliticalParty: require('./PoliticalParty'),
  },
  properties: {
    leaders: () => {},
    members: () => {},
  },
  //
  categories: {
    mapping: [
      'japanese brands',
      'american jazz composers',
      'scouting in the united states',
      'car brands',
      'government-owned airlines',
      'baptist denominations in north america',
      'baptist denominations established in the 20th century',
      'land-grant universities and colleges',
      'organizations based in washington, d.c.',
      'video game publishers',
      'defunct motor vehicle manufacturers of the united states',
      'alternative rock groups from california',
    ],
    patterns: [
      /(organi[sz]ations|publications) based in /,
      /(organi[sz]ations|publications|schools|awards) established in [0-9]{4}/,
      /(secondary|primary) schools/,
      /military units/,
      /magazines/,
      /organi[sz]ation stubs$/,
    ],
  },
  //
  descriptions: {
    patterns: [/(charity|organization|ngo)/],
  },
  //
  infoboxes: {
    mapping: [
      'airline',
      'broadcasting_network',
      'cbb_team',
      'choir',
      'college',
      'company',
      'dot-com_company',
      'film_awards',
      'film_festival',
      'football_league',
      'gaa_club',
      'government_agency',
      'government_cabinet',
      'journal',
      'laboratory',
      'law_enforcement_agency',
      'legislature',
      'library',
      'military_unit',
      'national_military',
      'ncaa_football_school',
      'newspaper',
      'nobility',
      'organization',
      'public_transit',
      'publisher',
      'radio_station',
      'rail_line',
      'rail_service',
      'record_label',
      'school_district',
      'sport_governing_body',
      'sports_league',
      'television_channel',
      'tv_channel',
      'u.s._cabinet',
      'u.s._legislation',
      'uk_legislation',
      'university',
      'v8_supercar_team',
      'former monarchy',
      'criminal organization',
      'radio station',
      'military unit',
      'government agency',
      'rail line',
      'record label',
      'school district',
      'tv channel',
      'sports league',
      'football league',
      'worldscouting',
      'sg rail',
      'law enforcement agency',
      'uk legislation',
      'public transit',
      'us university ranking',
      'television channel',
      'bus transit',
      'union',
      'broadcasting network',
      'christian denomination',
      'film awards',
      'gaa club',
      'fraternity',
      'rail',
      'rail service',
      'national military',
      'sport governing body',
      'political party/seats',
      'athletic conference',
      'film festival',
      'dot-com company',
      'india university ranking',
      'uk university rankings',
      'government cabinet',
    ],
    patterns: [],
  },
  //
  sections: {
    mapping: [
      'founding',
      'founders',
      'members',
      'athletics',
      'notable alumni',
      'academics',
      'campus',
      'organization',
      'student life',
      'rankings',
      'fleet',
      'research',
      'formation',
      'operations',
      'players',
      'alumni',
      'former members',
      'presidents',
      'membership',
      'current members',
    ],
    patterns: [],
  },
  //
  templates: {
    mapping: ['composition bar', 'fs player', 'y', 'n', 'rws'],
    patterns: [],
  },
  //
  titles: {
    mapping: [
      'group',
      'journal',
      'am',
      'fm',
      'wehrmacht',
      'tv channel',
      'british band',
      'organization',
      'airline',
      'publisher',
      'brand',
      'record label',
      'union army',
      'defunct',
      'tv network',
      'department store',
    ],
    patterns: [],
  },
}
