import Jurisdiction from './Jurisdiction/index.js'
import Structure from './Structure/index.js'
import BodyOfWater from './BodyOfWater.js'

export default {
  name: 'Place',
  children: {
    Jurisdiction,
    Structure,
    BodyOfWater,
  },
  //
  categories: {
    mapping: [],
    patterns: [
      /populated places/,
      /landforms of ./,
      /railway stations/,
      /parks in ./,
      / district$/,
      /geography stubs$/,
      /sports venue stubs$/,
    ],
  },
  //
  descriptions: {
    patterns: [],
  },
  //
  infoboxes: {
    mapping: [
      'amusement_park',
      'ancient_site',
      'australian_place',
      'belgium_municipality',
      'canada_electoral_district',
      'casino',
      'cemetery',
      'church',
      'cricket_ground',
      'dam',
      'ecoregion',
      'feature_on_mars',
      'finnish_municipality/population_count',
      'former_country',
      'former_subdivision',
      'french_commune',
      'gb_station',
      'geobox',
      'german_location',
      'golf_facility',
      'greek_dimos',
      'historic_site',
      'historic_subdivision',
      'hospital',
      'hotel',
      'islands',
      'israel_village',
      'italian_comune',
      'kommune',
      'launch_pad',
      'london_station',
      'lunar_crater',
      'military_memorial',
      'monument',
      'mountain_pass',
      'mountain_range',
      'mountain',
      'neighborhood_portland_or',
      'nycs',
      'oil_field',
      'park',
      'prison',
      'province_or_territory_of_canada',
      'road_small',
      'road',
      'russian_inhabited_locality',
      'russian_urban-type_settlement',
      'scotland_council_area',
      'settlement',
      'south_african_subplace_2011',
      'state',
      'station',
      'street',
      'temple',
      'theatre',
      'town_at',
      'u.s._congressional_district',
      'u.s._county',
      'u.s._metropolitan_area',
      'u.s._state',
      'uk_constituency_main',
      'uk_constituency',
      'uk_disused_station',
      'uk_place',
      'uk_station',
      'unesco_world_heritage_site',
      'university_of_notre_dame_residence_hall',
      'venue',
      'waterfall',
      'windmill',
      'world_heritage_site',
      'zoo',
    ],
    patterns: [],
  },
  //
  sections: {
    mapping: ['geography', 'geology', 'location', 'coat of arms'],
    patterns: [],
  },
  //
  templates: {
    mapping: [
      'coord',
      'weather box',
      'us census population',
      'jct',
      'geographic location',
      'representative',
      'historical populations',
      'wikivoyage-inline',
      'election box',
      'zh',
      'wide image',
    ],
    patterns: [/-geo-stub$/],
  },
  //
  titles: {
    mapping: [
      'cape verde',
      'cedar busway station',
      'delhi metro',
      'erie county, new york',
      'new jersey',
      'new orleans',
      'new york City Subway',
      'new york',
      'new zealand',
      'north carolina',
      'northern ireland',
      'sri lanka',
      'uk parliament constituency',
      'united kingdom',
      'united states',
      'alaska',
      'argentina',
      'arkansas',
      'australia',
      'barbados',
      'brazil',
      'california',
      'canada',
      'chad',
      'chicago',
      'colombia',
      'connecticut',
      'dominica',
      'edmonton',
      'france',
      'georgia',
      'india',
      'israel',
      'japan',
      'manhattan',
      'michigan',
      'nigeria',
      'oklahoma',
      'ontario',
      'pennsylvania',
      'portugal',
      'province',
      'spain',
      'sudan',
      'texas',
      'uk',
      'va',
      'Virginia',
      'volcano',
      'washington',
    ],
    patterns: [],
  },
}
