module.exports = {
  id: 'CreativeWork',
  children: {
    Album: require('./Album'),
    Book: require('./Book'),
    Film: require('./Film'),
    TVShow: require('./TVShow'),
    Play: require('./Play'),
    VideoGame: require('./VideoGame'),
  },
  //
  properties: {
    genre: () => {},
  },
  //
  categories: {
    mapping: [
      'operas',
      'american science fiction novels',
      'broadway musicals',
      'debut novels',
      'the twilight zone (1959 tv series) episodes',
      'united states national recording registry recordings',
      'macos games',
      'virtual console games for wii u',
      'american monthly magazines',
      'broadway plays',
      'interactive achievement award winners',
      'doubleday (publisher) books',
      '19th-century classical composers',
      'film soundtracks',
      'universal deluxe editions',
      'best picture academy award winners',
      'shōnen manga',
      'west end musicals',
      'sequel novels',
      'dystopian novels',
      'american comic strips',
      'american road movies',
      'chemical elements',
      'amstrad cpc games',
      'neo-noir',
      'fiction with unreliable narrators',
      'best drama picture golden globe winners',
      'adventure anime and manga',
    ],
    patterns: [],
  },
  //
  descriptions: {
    patterns: [],
  },
  //
  infoboxes: {
    mapping: [
      'artwork',
      'book_series',
      'broadcast',
      'comic_book_title',
      'comic_strip',
      'doctor_who_episode',
      'hollywood_cartoon',
      'magazine',
      'musical',
      'musical_composition',
      'opera',
      'painting',
      'radio_show',
      'song',
      'song_contest_entry',
      'television_episode',
      'television_season',
      'treaty',
      'video_game',
      'anthem',
      'television episode',
      'comic book title',
      'song contest entry',
      'short story',
      'hollywood cartoon',
      'radio show',
      'simpsons episode',
      'musical composition',
      'book series',
      'comic strip',
      'television season',
      'comics organization',
      'doctor who episode',
      'animanga/other',
      'graphic novel',
      'rpg',
      'big finish',
      'vg series',
      'name module',
      'comics story arc',
      'video game series',
      'futurama episode',
      'comics character and title',
      'comics meta series',
      'webcomic',
      'the goodies episode',
      'audio drama',
      'sw comics',
      'media franchise',
      'folk tale',
    ],
    patterns: [],
  },
  //
  sections: {
    mapping: [
      'plot',
      'reception',
      'charts',
      'release',
      'plot summary',
      'gameplay',
      'characters',
      'box office',
      'accolades',
      'soundtrack',
      'adaptations',
      'synopsis',
      'home media',
      'weekly charts',
      'themes',
      'publication history',
      'filming',
      'year-end charts',
      'casting',
      'release and reception',
      'commercial performance',
      'composition',
      'album',
      'setting',
      'chart positions',
      'release history',
      'charts and certifications',
      'sequels',
      'chart performance',
      'sequel',
      'recordings',
      'story',
      'editions',
      'in other media',
    ],
    patterns: [],
  },
  //
  templates: {
    mapping: [
      'rating',
      'certification table entry',
      'albumchart',
      'music',
      'album ratings',
      'album chart',
      'singles',
      'isbnt',
      'singlechart',
      'tcmdb title',
      'mojo title',
      'based on',
      'amg movie',
      'duration',
    ],
    patterns: [/-song-stub$/],
  },
  //
  titles: {
    mapping: [
      'season 2',
      'season 3',
      'season 4',
      'season 5',
      'the twilight zone',
      'ballet',
      'magazine',
      'miniseries',
      'music',
      'opera',
      'painting',
      'series',
      'single',
      'song',
      'soundtrack',
      'ep',
      'comics',
      'musical',
      'manga',
      'star trek: the next generation',
      'star trek: deep space nine',
      'buffy the vampire slayer',
      'angel',
      'the outer limits',
      'star trek: voyager',
      'short story',
      'seinfeld',
      'star trek: enterprise',
      'poem',
      'tv',
      'uk series',
      'doctor who',
      'david bowie song',
      'caravaggio',
      'the beach boys song',
      'video',
      'audio drama',
      'babylon 5',
      'madonna song',
    ],
    patterns: [],
  },
}
