module.exports = {
  'living people': 'Person',
  'possibly living people': 'Person',
  'grammy award winners': 'Organization/MusicalGroup',
  'musical quartets': 'Organization/MusicalGroup',
  'musical duos': 'Organization/MusicalGroup',
  'musical trios': 'Organization/MusicalGroup',

  // learned march 30
  'dos games': 'CreativeWork/VideoGame',
  'virtual console games': 'CreativeWork/VideoGame',
  'mac os games': 'CreativeWork/VideoGame',
  operas: 'CreativeWork',
  'american science fiction novels': 'CreativeWork',
  'amiga games': 'CreativeWork/VideoGame',
  'broadway musicals': 'CreativeWork',
  'debut novels': 'CreativeWork',
  'the twilight zone (1959 tv series) episodes': 'CreativeWork',
  'arcade games': 'CreativeWork/VideoGame',
  'united states national recording registry recordings': 'CreativeWork',
  'commodore 64 games': 'CreativeWork/VideoGame',
  'nintendo entertainment system games': 'CreativeWork/VideoGame',
  'macos games': 'CreativeWork',
  'playstation (console) games': 'CreativeWork/VideoGame',
  'virtual console games for wii u': 'CreativeWork',
  'ios games': 'CreativeWork/VideoGame',
  'super nintendo entertainment system games': 'CreativeWork/VideoGame',
  'video game sequels': 'CreativeWork/VideoGame',
  'american monthly magazines': 'CreativeWork',
  'broadway plays': 'CreativeWork',
  'game boy advance games': 'CreativeWork/VideoGame',
  'first-person shooters': 'CreativeWork/VideoGame',
  'playstation network games': 'CreativeWork/VideoGame',
  'interactive achievement award winners': 'CreativeWork',
  'linux games': 'CreativeWork/VideoGame',
  'atari st games': 'CreativeWork/VideoGame',
  'doubleday (publisher) books': 'CreativeWork',
  '19th-century classical composers': 'CreativeWork',
  'film soundtracks': 'CreativeWork',
  'universal deluxe editions': 'CreativeWork',
  'playstation 2 games': 'CreativeWork/VideoGame',
  'best picture academy award winners': 'CreativeWork',
  'game boy games': 'CreativeWork/VideoGame',
  'shōnen manga': 'CreativeWork',
  'zx spectrum games': 'CreativeWork/VideoGame',
  'west end musicals': 'CreativeWork',
  'sequel novels': 'CreativeWork',
  'dystopian novels': 'CreativeWork',
  'american comic strips': 'CreativeWork',
  'american road movies': 'CreativeWork',
  'chemical elements': 'CreativeWork',
  'amstrad cpc games': 'CreativeWork',
  'mario universe games': 'CreativeWork/VideoGame',
  'neo-noir': 'CreativeWork',
  'multiplayer online games': 'CreativeWork/VideoGame',
  'mobile games': 'CreativeWork/VideoGame',
  'android (operating system) games': 'CreativeWork/VideoGame',
  'platform games': 'CreativeWork/VideoGame',
  'fiction with unreliable narrators': 'CreativeWork',
  'best drama picture golden globe winners': 'CreativeWork',
  'adventure anime and manga': 'CreativeWork',
  'albums recorded at abbey road studios': 'CreativeWork/Album',
  'xbox 360 live arcade games': 'CreativeWork/VideoGame',
  'sega genesis games': 'CreativeWork/VideoGame',

  //learned events
  'years in literature': 'Event',
  'years in music': 'Event',
  'years in film': 'Event',
  'united states supreme court cases': 'Event',
  'leap years in the gregorian calendar': 'Event',
  "governor general's awards": 'Event',
  'eurovision song contest by year': 'Event',
  'grammy awards ceremonies': 'Event',
  'united kingdom in the eurovision song contest': 'Event',
  'manned soyuz missions': 'Event',
  'american civil liberties union litigation': 'Event',
  may: 'Event',
  october: 'Event',
  'missions to the moon': 'Event',
  'nasa space probes': 'Event',
  'world war ii british commando raids': 'Event',
  july: 'Event',
  december: 'Event',
  'wars involving the united kingdom': 'Event/MilitaryConflict',
  september: 'Event',
  november: 'Event',
  january: 'Event',
  june: 'Event',
  august: 'Event',
  april: 'Event',
  february: 'Event',
  march: 'Event',
  'conflicts in 1944': 'Event',
  'human spaceflights': 'Event',
  'missions to mars': 'Event',
  'derelict space probes': 'Event',
  'luna program': 'Event',
  'proxy wars': 'Event/MilitaryConflict',
  'conflicts in 1942': 'Event',
  'special air service': 'Event',
  'spacecraft launched by delta ii rockets': 'Event',
  'soft landings on the moon': 'Event',
  'may observances': 'Event',
  '1904 summer olympics events': 'Event/SportsEvent',
  '1900 summer olympics events': 'Event/SportsEvent',
  'space shuttle missions': 'Event',
  'apollo program missions': 'Event',
  'spacecraft launched in 1962': 'Event',
  'spacecraft launched by titan rockets': 'Event',
  'first events': 'Event',
  'recent years': 'Event',
  'elections not won by the popular vote winner': 'Event',
  'conflicts in 1864': 'Event',
  '1862 in the american civil war': 'Event',
  'new zealand wars': 'Event/MilitaryConflict',
  'battles between england and scotland': 'Event/MilitaryConflict',
  '2002 winter olympics events': 'Event/SportsEvent',
  'spacecraft launched by atlas-centaur rockets': 'Event',
  'space observatories': 'Event',
  'new york (state) in the american revolution': 'Event',
  'march observances': 'Event',
  'public holidays in the united states': 'Event',
  'conflicts in 1943': 'Event/MilitaryConflict',
  'spacecraft launched in 1966': 'Event',
  'last stand battles': 'Event/MilitaryConflict',
  '1944 in france': 'Event',
  'battles and conflicts without fatalities': 'Event/MilitaryConflict',
  'manned missions to the moon': 'Event',
  'sample return missions': 'Event',
  '1973 in spaceflight': 'Event',
  'guerrilla wars': 'Event/MilitaryConflict',
  'retired atlantic hurricanes': 'Event/Disaster',
  'december observances': 'Event',
  '20th century american trials': 'Event',
  'african-american civil rights movement (1954–68)': 'Event',
  '20th-century conflicts': 'Event/MilitaryConflict',
  'presidential elections in ireland': 'Event/Election',
  'spacecraft launched in 1973': 'Event',
  'october observances': 'Event',
  'spring holidays': 'Event',
  'years in aviation': 'Event',
  'national days': 'Event',
  'project gemini missions': 'Event',
  'spacecraft launched in 1965': 'Event',
  '20th-century revolutions': 'Event/MilitaryConflict',
  'spacecraft launched in 1971': 'Event',
  'fifa world cup tournaments': 'Event/SportsEvent',
  'summer holidays': 'Event',
  'sieges involving japan': 'Event/MilitaryConflict',
  'lunar flybys': 'Event',
  'apollo program': 'Event',
  'revolution-based civil wars': 'Event/MilitaryConflict',

  // learned organisms
  'taxa named by carl linnaeus': 'Organism',
  'ornamental trees': 'Organism',
  'birds by common name': 'Organism',
  'living fossils': 'Organism',
  'taxa named by john edward gray': 'Organism',
  phelsuma: 'Organism',
  multituberculates: 'Organism',
  'angiosperm orders': 'Organism',
  cimolodonts: 'Organism',
  'urban animals': 'Organism',
  flowers: 'Organism',
  geckos: 'Organism',
  herbs: 'Organism',
  spices: 'Organism',
  skinks: 'Organism',
  'cretaceous mammals': 'Organism',
  'commercial fish': 'Organism',
  'paleocene mammals': 'Organism',
  'bird families': 'Organism',
  'edible nuts and seeds': 'Organism',
  'invasive plant species': 'Organism',
  'leaf vegetables': 'Organism',
  'root vegetables': 'Organism',
  'corvus (genus)': 'Organism',
  'insects in culture': 'Organism',
  ducks: 'Organism',
  agamidae: 'Organism',
  'edge species': 'Organism',
  'tropical fruit': 'Organism',
  pinus: 'Organism',
  'tropical agriculture': 'Organism',
  'indian spices': 'Organism',
  'paleocene genus extinctions': 'Organism',
  'epiphytic orchids': 'Organism',
  crops: 'Organism',
  'fruits originating in asia': 'Organism',
  calidris: 'Organism',
  ptilodontoids: 'Organism',
  'plants and pollinators': 'Organism',
  'mammal families': 'Organism',
  'marine edible fish': 'Organism',
  'taxa named by leopold fitzinger': 'Organism',
  setophaga: 'Organism',
  shorebirds: 'Organism',
  berries: 'Organism',
  megafauna: 'Organism',
  'animal dance': 'Organism',
  'animal phyla': 'Organism',
  'american inventions': 'Organism',
  entheogens: 'Organism',
  'crops originating from the americas': 'Organism',
  'non-timber forest products': 'Organism',
  geese: 'Organism'
}
