module.exports = {
  'living people': 'Person',
  'possibly living people': 'Person',
  'musical quartets': 'Organization/MusicalGroup',
  'musical duos': 'Organization/MusicalGroup',
  'musical trios': 'Organization/MusicalGroup',

  // learned march 30
  'dos games': 'CreativeWork/VideoGame',
  'virtual console games': 'CreativeWork/VideoGame',
  'mac os games': 'CreativeWork/VideoGame',
  operas: 'CreativeWork',
  'american science fiction novels': 'CreativeWork',
  'amiga games': 'CreativeWork/VideoGame',
  'broadway musicals': 'CreativeWork',
  'debut novels': 'CreativeWork',
  'the twilight zone (1959 tv series) episodes': 'CreativeWork',
  'arcade games': 'CreativeWork/VideoGame',
  'united states national recording registry recordings': 'CreativeWork',
  'commodore 64 games': 'CreativeWork/VideoGame',
  'nintendo entertainment system games': 'CreativeWork/VideoGame',
  'macos games': 'CreativeWork',
  'playstation (console) games': 'CreativeWork/VideoGame',
  'virtual console games for wii u': 'CreativeWork',
  'ios games': 'CreativeWork/VideoGame',
  'super nintendo entertainment system games': 'CreativeWork/VideoGame',
  'video game sequels': 'CreativeWork/VideoGame',
  'american monthly magazines': 'CreativeWork',
  'broadway plays': 'CreativeWork',
  'game boy advance games': 'CreativeWork/VideoGame',
  'first-person shooters': 'CreativeWork/VideoGame',
  'playstation network games': 'CreativeWork/VideoGame',
  'interactive achievement award winners': 'CreativeWork',
  'linux games': 'CreativeWork/VideoGame',
  'atari st games': 'CreativeWork/VideoGame',
  'doubleday (publisher) books': 'CreativeWork',
  '19th-century classical composers': 'CreativeWork',
  'film soundtracks': 'CreativeWork',
  'universal deluxe editions': 'CreativeWork',
  'playstation 2 games': 'CreativeWork/VideoGame',
  'best picture academy award winners': 'CreativeWork',
  'game boy games': 'CreativeWork/VideoGame',
  'shōnen manga': 'CreativeWork',
  'zx spectrum games': 'CreativeWork/VideoGame',
  'west end musicals': 'CreativeWork',
  'sequel novels': 'CreativeWork',
  'dystopian novels': 'CreativeWork',
  'american comic strips': 'CreativeWork',
  'american road movies': 'CreativeWork',
  'chemical elements': 'CreativeWork',
  'amstrad cpc games': 'CreativeWork',
  'mario universe games': 'CreativeWork/VideoGame',
  'neo-noir': 'CreativeWork',
  'multiplayer online games': 'CreativeWork/VideoGame',
  'mobile games': 'CreativeWork/VideoGame',
  'android (operating system) games': 'CreativeWork/VideoGame',
  'platform games': 'CreativeWork/VideoGame',
  'fiction with unreliable narrators': 'CreativeWork',
  'best drama picture golden globe winners': 'CreativeWork',
  'adventure anime and manga': 'CreativeWork',
  'albums recorded at abbey road studios': 'CreativeWork/Album',
  'xbox 360 live arcade games': 'CreativeWork/VideoGame',
  'sega genesis games': 'CreativeWork/VideoGame',

  //learned events
  'years in literature': 'Event',
  'years in music': 'Event',
  'years in film': 'Event',
  'united states supreme court cases': 'Event',
  'leap years in the gregorian calendar': 'Event',
  "governor general's awards": 'Event',
  'eurovision song contest by year': 'Event',
  'grammy awards ceremonies': 'Event',
  'united kingdom in the eurovision song contest': 'Event',
  'manned soyuz missions': 'Event',
  'american civil liberties union litigation': 'Event',
  may: 'Event',
  october: 'Event',
  'missions to the moon': 'Event',
  'nasa space probes': 'Event/SpaceMission',
  'world war ii british commando raids': 'Event',
  july: 'Event',
  december: 'Event',
  'wars involving the united kingdom': 'Event/MilitaryConflict',
  september: 'Event',
  november: 'Event',
  january: 'Event',
  june: 'Event',
  august: 'Event',
  april: 'Event',
  february: 'Event',
  march: 'Event',
  'conflicts in 1944': 'Event',
  'human spaceflights': 'Event/SpaceMission',
  'missions to mars': 'Event',
  'derelict space probes': 'Event/SpaceMission',
  'luna program': 'Event',
  'proxy wars': 'Event/MilitaryConflict',
  'conflicts in 1942': 'Event',
  'special air service': 'Event',
  'spacecraft launched by delta ii rockets': 'Event/SpaceMission',
  'soft landings on the moon': 'Event',
  'may observances': 'Event',
  '1904 summer olympics events': 'Event/SportsEvent',
  '1900 summer olympics events': 'Event/SportsEvent',
  'space shuttle missions': 'Event/SpaceMission',
  'apollo program missions': 'Event/SpaceMission',
  'spacecraft launched in 1962': 'Event/SpaceMission',
  'spacecraft launched by titan rockets': 'Event/SpaceMission',
  'first events': 'Event',
  'recent years': 'Event',
  'elections not won by the popular vote winner': 'Event',
  'conflicts in 1864': 'Event',
  '1862 in the american civil war': 'Event',
  'new zealand wars': 'Event/MilitaryConflict',
  'battles between england and scotland': 'Event/MilitaryConflict',
  '2002 winter olympics events': 'Event/SportsEvent',
  'spacecraft launched by atlas-centaur rockets': 'Event/SpaceMission',
  'space observatories': 'Event/SpaceMission',
  'new york (state) in the american revolution': 'Event',
  'march observances': 'Event',
  'public holidays in the united states': 'Event',
  'conflicts in 1943': 'Event/MilitaryConflict',
  'spacecraft launched in 1966': 'Event/SpaceMission',
  'last stand battles': 'Event/MilitaryConflict',
  '1944 in france': 'Event',
  'battles and conflicts without fatalities': 'Event/MilitaryConflict',
  'manned missions to the moon': 'Event/SpaceMission',
  'sample return missions': 'Event/SpaceMission',
  '1973 in spaceflight': 'Event/SpaceMission',
  'guerrilla wars': 'Event/MilitaryConflict',
  'retired atlantic hurricanes': 'Event/Disaster',
  'december observances': 'Event',
  '20th century american trials': 'Event',
  'african-american civil rights movement (1954–68)': 'Event',
  '20th-century conflicts': 'Event/MilitaryConflict',
  'presidential elections in ireland': 'Event/Election',
  'spacecraft launched in 1973': 'Event/SpaceMission',
  'october observances': 'Event',
  'spring holidays': 'Event',
  'years in aviation': 'Event',
  'national days': 'Event',
  'project gemini missions': 'Event/SpaceMission',
  'spacecraft launched in 1965': 'Event/SpaceMission',
  '20th-century revolutions': 'Event/MilitaryConflict',
  'spacecraft launched in 1971': 'Event/SpaceMission',
  'fifa world cup tournaments': 'Event/SpaceMission',
  'summer holidays': 'Event',
  'sieges involving japan': 'Event/MilitaryConflict',
  'lunar flybys': 'Event/SpaceMission',
  'apollo program': 'Event',
  'revolution-based civil wars': 'Event/MilitaryConflict',

  // learned organisms
  'taxa named by carl linnaeus': 'Organism',
  'ornamental trees': 'Organism',
  'birds by common name': 'Organism',
  'living fossils': 'Organism',
  'taxa named by john edward gray': 'Organism',
  phelsuma: 'Organism',
  multituberculates: 'Organism',
  'angiosperm orders': 'Organism',
  cimolodonts: 'Organism',
  'urban animals': 'Organism',
  flowers: 'Organism',
  geckos: 'Organism',
  herbs: 'Organism',
  spices: 'Organism',
  skinks: 'Organism',
  'cretaceous mammals': 'Organism',
  'commercial fish': 'Organism',
  'paleocene mammals': 'Organism',
  'bird families': 'Organism',
  'edible nuts and seeds': 'Organism',
  'invasive plant species': 'Organism',
  'leaf vegetables': 'Organism',
  'root vegetables': 'Organism',
  'corvus (genus)': 'Organism',
  'insects in culture': 'Organism',
  ducks: 'Organism',
  agamidae: 'Organism',
  'edge species': 'Organism',
  'tropical fruit': 'Organism',
  pinus: 'Organism',
  'tropical agriculture': 'Organism',
  'indian spices': 'Organism',
  'paleocene genus extinctions': 'Organism',
  'epiphytic orchids': 'Organism',
  crops: 'Organism',
  'fruits originating in asia': 'Organism',
  calidris: 'Organism',
  ptilodontoids: 'Organism',
  'plants and pollinators': 'Organism',
  'mammal families': 'Organism',
  'marine edible fish': 'Organism',
  'taxa named by leopold fitzinger': 'Organism',
  setophaga: 'Organism',
  shorebirds: 'Organism',
  berries: 'Organism',
  megafauna: 'Organism',
  'animal dance': 'Organism',
  'animal phyla': 'Organism',
  'american inventions': 'Organism',
  entheogens: 'Organism',
  'crops originating from the americas': 'Organism',
  'non-timber forest products': 'Organism',
  geese: 'Organism',

  // person-musician
  'american male guitarists': 'Person/Artist',
  'american singer-songwriters': 'Person/Artist',
  'american male singers': 'Person/Artist',
  'american rock singers': 'Person/Artist',
  'american rock guitarists': 'Person/Artist',
  '21st-century american singers': 'Person/Artist',
  'lead guitarists': 'Person/Artist',
  'african-american musicians': 'Person/Artist',
  'english male singers': 'Person/Artist',
  'american male singer-songwriters': 'Person/Artist',
  'american rock songwriters': 'Person/Artist',
  'american record producers': 'Person/Artist',
  'american country singer-songwriters': 'Person/Artist',
  '20th-century american guitarists': 'Person/Artist',
  'english songwriters': 'Person/Artist',
  '20th-century american pianists': 'Person/Artist',
  'songwriters from new york (state)': 'Person/Artist',
  'african-american singers': 'Person/Artist',
  'american blues singers': 'Person/Artist',
  'american pop singers': 'Person/Artist',
  'male guitarists': 'Person/Artist',
  'american country singers': 'Person/Artist',
  'blues hall of fame inductees': 'Person/Artist',
  'american male songwriters': 'Person/Artist',
  'songwriters from california': 'Person/Artist',
  'english rock guitarists': 'Person/Artist',
  'american folk singers': 'Person/Artist',
  'english rock singers': 'Person/Artist',
  'english singer-songwriters': 'Person/Artist',
  'african-american male rappers': 'Person/Artist',
  'african-american jazz musicians': 'Person/Artist',
  '20th-century english singers': 'Person/Artist',
  'american female singer-songwriters': 'Person/Artist',
  'jewish american musicians': 'Person/Artist',
  'american blues guitarists': 'Person/Artist',
  '20th-century conductors (music)': 'Person/Artist',
  'american female singers': 'Person/Artist',
  'american jazz bandleaders': 'Person/Artist',
  'american jazz pianists': 'Person/Artist',
  'american soul singers': 'Person/Artist',
  'american female guitarists': 'Person/Artist',
  'american multi-instrumentalists': 'Person/Artist',
  'american country guitarists': 'Person/Artist',
  'english record producers': 'Person/Artist',
  'songwriters from texas': 'Person/Artist',
  'american composers': 'Person/Artist',
  'singers from california': 'Person/Artist',
  'american folk guitarists': 'Person/Artist',
  'lgbt singers': 'Person/Artist',
  'american buskers': 'Person/Artist',
  'guitarists from california': 'Person/Artist',
  'feminist musicians': 'Person/Artist',
  'big band bandleaders': 'Person/Artist',
  '20th-century composers': 'Person/Artist',
  'african-american songwriters': 'Person/Artist',
  'british rhythm and blues boom musicians': 'Person/Artist',
  'alternative rock singers': 'Person/Artist',
  '21st-century american guitarists': 'Person/Artist',
  'american alternative rock musicians': 'Person/Artist',
  'musicians from los angeles': 'Person/Artist',
  'rhythm guitarists': 'Person/Artist',
  'american session musicians': 'Person/Artist',
  'jazz musicians from new orleans': 'Person/Artist',
  'alternative rock guitarists': 'Person/Artist',
  '20th-century women musicians': 'Person/Artist',
  'male film score composers': 'Person/Artist',
  'african-american singer-songwriters': 'Person/Artist',
  'american jazz singers': 'Person/Artist',
  '21st-century english singers': 'Person/Artist',
  'singers from new york city': 'Person/Artist',
  'american acoustic guitarists': 'Person/Artist',
  'musicians from new york city': 'Person/Artist',
  'slide guitarists': 'Person/Artist',
  'guitarists from texas': 'Person/Artist',

  // org
  'companies listed on the new york stock exchange': 'Organization/Company',
  'football clubs in england': 'Organization/SportsTeam',
  'musical quintets': 'Organization/MusicalGroup',
  'english rock music groups': 'Organization/MusicalGroup',
  'english new wave musical groups': 'Organization/MusicalGroup',
  'jazz record labels': 'Organization/Company',
  'video game development companies': 'Organization/Company',
  'american record labels': 'Organization/Company',
  'english football league clubs': 'Organization/SportsTeam',
  'companies listed on nasdaq': 'Organization/Company',
  'african-american musical groups': 'Organization/MusicalGroup',
  'japanese brands': 'Organization',
  'video game companies of the united states': 'Organization/Company',
  'american jazz composers': 'Organization',
  '21st-century american musicians': 'Organization/MusicalGroup',
  'companies formerly listed on the london stock exchange': 'Organization/Company',
  'southern football league clubs': 'Organization/SportsTeam',
  'multinational companies headquartered in the united states': 'Organization/Company',
  'scouting in the united states': 'Organization',
  'car brands': 'Organization',
  'american alternative metal musical groups': 'Organization/MusicalGroup',
  'government-owned airlines': 'Organization',
  'football clubs in scotland': 'Organization/SportsTeam',
  'baptist denominations in north america': 'Organization',
  'baptist denominations established in the 20th century': 'Organization',
  'land-grant universities and colleges': 'Organization',
  'companies listed on the tokyo stock exchange': 'Organization/Company',
  'organizations based in washington, d.c.': 'Organization',
  'premier league clubs': 'Organization/SportsTeam',
  'national basketball association teams': 'Organization/SportsTeam',
  'social democratic parties': 'Organization/PoliticalParty',
  're-established companies': 'Organization/Company',
  'video game publishers': 'Organization',
  'companies based in new york city': 'Organization/Company',
  'defunct video game companies': 'Organization/Company',
  'companies formed by merger': 'Organization/Company',
  'english pop music groups': 'Organization/MusicalGroup',
  'defunct motor vehicle manufacturers of the united states': 'Organization',
  'alternative rock groups from california': 'Organization',
  'entertainment companies based in california': 'Organization/Company',
  'art rock musical groups': 'Organization/MusicalGroup',
  'english post-punk music groups': 'Organization/MusicalGroup',

  // learned people
  'year of birth unknown': 'Person',
  'fellows of the royal society': 'Person',
  'members of the privy council of the united kingdom': 'Person',
  'uk mps 2001–05': 'Person/Politician',
  'uk mps 1997–2001': 'Person/Politician',
  '20th-century american novelists': 'Person/Artist',
  'american people of english descent': 'Person',
  'american male novelists': 'Person/Artist',
  'uk mps 2005–10': 'Person/Politician',
  'guggenheim fellows': 'Person',
  '20th-century american writers': 'Person',
  'harvard university alumni': 'Person',
  'fellows of the american academy of arts and sciences': 'Person/Academic',
  'american military personnel of world war ii': 'Person',
  '19th-century male writers': 'Person',
  'knights bachelor': 'Person',
  'american roman catholics': 'Person',
  'uk mps 1992–97': 'Person/Politician',
  'american male writers': 'Person',
  'roman catholic monarchs': 'Person/ReligiousFigure',
  '20th-century women writers': 'Person',
  'labour party (uk) mps for english constituencies': 'Person/Politician',
  '20th-century male writers': 'Person',
  'german male writers': 'Person',
  'knights of the garter': 'Person',
  'conservative party (uk) mps for english constituencies': 'Person/Politician',
  'presidential medal of freedom recipients': 'Person',
  'uk mps 1987–92': 'Person/Politician',
  'american film directors': 'Person/Artist',
  '21st-century american novelists': 'Person/Artist',
  'uk mps 2010–15': 'Person/Politician',
  'american film producers': 'Person/Artist',
  'members of the united states national academy of sciences': 'Person/Academic',
  'commanders of the order of the british empire': 'Person',
  'democratic party members of the united states house of representatives': 'Person/Politician',
  'people educated at eton college': 'Person',
  'american male screenwriters': 'Person/Artist',
  '21st-century american writers': 'Person',
  'republican party members of the united states house of representatives': 'Person/Politician',
  popes: 'Person/ReligiousFigure',
  'alumni of trinity college, cambridge': 'Person',
  'french male writers': 'Person',
  'foreign members of the royal society': 'Person',
  'american science fiction writers': 'Person/Artist',
  'american people of scottish descent': 'Person',
  'american memoirists': 'Person',
  'members of the french academy of sciences': 'Person',
  'jewish american writers': 'Person',
  '20th-century english novelists': 'Person/Artist',
  'uk mps 1983–87': 'Person/Politician',
  'united states army soldiers': 'Person',
  'officers of the order of the british empire': 'Person',
  'deaths from pneumonia': 'Person',
  'burials at père lachaise cemetery': 'Person',
  'deaths from cancer in california': 'Person',
  'year of birth missing (living people)': 'Person',
  'democratic party state governors of the united states': 'Person/Politician',
  'english male poets': 'Person/Artist',
  'knights of the golden fleece': 'Person',
  'american male short story writers': 'Person/Artist',
  'columbia university alumni': 'Person',
  'alumni of the university of edinburgh': 'Person',
  'american political writers': 'Person/Artist',
  'california republicans': 'Person/Politician',
  'members of the royal swedish academy of sciences': 'Person/Academic',
  'american people of russian-jewish descent': 'Person',
  '20th-century american short story writers': 'Person/Academic',
  'yale university alumni': 'Person',
  'italian popes': 'Person/ReligiousFigure',
  'american atheists': 'Person',
  'people of the tudor period': 'Person',
  'tony award winners': 'Person',
  'male actors from new york city': 'Person/Actor',
  'british secretaries of state': 'Person/Politician',
  'democratic party united states senators': 'Person/Politician',
  'members of the académie française': 'Person',
  'united states army officers': 'Person',
  'persons of national historic significance (canada)': 'Person',
  'uk mps 2015–17': 'Person/Politician',
  '20th-century american businesspeople': 'Person',
  'american journalists': 'Person',
  'american television producers': 'Person',
  'writers from new york city': 'Person',
  'republican party united states senators': 'Person/Politician',
  'american male journalists': 'Person',
  '21st-century women writers': 'Person',
  'american male comedians': 'Person',
  'american nobel laureates': 'Person/Academic',
  'republican party state governors of the united states': 'Person/Politician',
  'princeton university alumni': 'Person',
  'university of paris alumni': 'Person',
  'american episcopalians': 'Person',
  'american women novelists': 'Person',
  'phi beta kappa members': 'Person',
  '20th-century american poets': 'Person',
  'harvard university faculty': 'Person/Academic',
  'english male novelists': 'Person/Artist',
  'california democrats': 'Person/Politician',
  'uk mps 1979–83': 'Person/Politician',
  'bafta winners (people)': 'Person',
  'english male writers': 'Person',
  'uk mps 2017–': 'Person/Politician',
  "members of the queen's privy council for canada": 'Person',
  'vaudeville performers': 'Person/Artist',
  'american presbyterians': 'Person'
}
