export default {
  '·': '·',
  dot: '·',
  middot: '·',
  '•': ' • ',
  ',': ',',
  '=': '=',
  '1/2': '1⁄2',
  '1/3': '1⁄3',
  '2/3': '2⁄3',
  '1/4': '1⁄4',
  '3/4': '3⁄4',
  '–': '–',
  ndash: '–',
  'en dash': '–',
  'spaced ndash': ' – ',
  '—': '—',
  mdash: '—',
  spd: ' – ',
  'em dash': '—',
  'number sign': '#',
  'hash-tag': '#',
  ibeam: 'I',
  '&': '&',
  ';': ';',
  ampersand: '&',
  dagger: '†',
  'double-dagger': '‡',
  snds: ' – ',
  snd: ' – ',
  '^': ' ',
  '!': '|',
  "'": `'`,
  '\\': ' /',
  '`': '`',
  // bracket: '[',
  '[': '[',
  '*': '*',
  asterisk: '*',
  'long dash': '———',
  clear: '\n\n',
  'h.': 'ḥ',
  profit: '▲',
  // loss: '▼',
  // gain: '▲',
  ell: 'ℓ',
  '1~': '~',
  '2~': '~~',
  '3~': '~~~',
  '4~': '~~~~',
  '5~': '~~~~~',
  // some emoji replacements
  goldmedal: '🥇',
  silvermedal: '🥈',
  bronzemedal: '🥉',
  done: '✅',
  xmark: '❌',
  checked: '✔️',
  'thumbs up': '👍',
  'thumbs down': '👎',
  minusplus: '∓',
  plusminus: '±',

  // 'hbeff début': '{|-\n',
  egiptekas: '{|-\n',
  langle: '⟨',
  rangle: '⟩',
  epsilon: 'ε',
  xi: '𝜉',
  Φ: 'Φ',
  phi: '𝜙',
  varphi: '𝜑',
  upsilon: '𝜐',
  tau: '𝜏',
  varsigma: '𝜍',
  sigma: '𝜎',
  pi: 'π',
  mu: '𝜇',
  lambda: '𝜆',
  kappa: '𝜘',
  vartheta: '𝜗',
  theta: '𝜃',
  varepsilon: '𝜀',
  gamma: '𝛾',
  shy: '-',
  mdashb: '—‌',
  'spaced en dash': ' –',
  'spaced en dash space': ' – ',
  'zero width joiner em dash zero width non joiner': '—‌',
  colon: ':',
  pipe: '|',
  '-?': '?',
  zwsp: ' ',
  sp: ' ',
  px2: ' ',
  indent: '    ',
  nb5: '    ',
  ns: '    ',
  quad: '    ',
  spaces: '    ',
  in5: '     ',
  tombstone: '◻',
  // increase: '▲',
  // decrease: '▼',
  'no.': '#',
  'thin space': ' ',
  thinspace: ' ',
  'very thin space': ' ',
  'word joiner': ' ',
  'figure space': ' ',
  'zero width joiner': ' ',
  'hair space': ' ',
  'narrow no-break space': ' ',
  'non breaking hyphen': '-',
  '!((': '[[',
  '))!': ']]',
  '(': '{',
  '((': '{{',
  '(((': '{{{',
  ')': '}',
  '))': '}}',
  ')))': '}}}',
  '(!': '{|',
  '!+': '|+',
  '!-': '|-',
  '!)': '|}',
  flat: '♭',
  sharp: '♯',
  lbf: 'lbF',
  lbm: 'lbm',
}
