export default {
  '·': '·',
  dot: '·',
  middot: '·',
  '•': ' • ',
  ',': ',',
  '1/2': '1⁄2',
  '1/3': '1⁄3',
  '2/3': '2⁄3',
  '1/4': '1⁄4',
  '3/4': '3⁄4',
  '–': '–',
  ndash: '–',
  'en dash': '–',
  'spaced ndash': ' – ',
  '—': '—',
  mdash: '—',
  'em dash': '—',
  'number sign': '#',
  ibeam: 'I',
  '&': '&',
  ';': ';',
  ampersand: '&',
  snds: ' – ',
  snd: ' – ',
  '^': ' ',
  '!': '|',
  '\\': ' /',
  '`': '`',
  '=': '=',
  bracket: '[',
  '[': '[',
  '*': '*',
  asterisk: '*',
  'long dash': '———',
  clear: '\n\n',
  'h.': 'ḥ',
  profit: '▲',
  loss: '▼',
  gain: '▲',
}
