// https://en.m.wikipedia.org/wiki/Template:Stub#/languages
export default [
  'aboç',
  'ahurhire',
  'aizmetnis',
  'amud',
  'avixo de spigaso',
  'begin',
  'beginnetje',
  'bibarilo',
  'borrador',
  'buáng-nàng-hâ',
  'bun',
  'buntato',
  'c-supranu',
  'cahrot',
  'chala',
  'choutchette',
  'ciot',
  'csonk',
  'cung',
  'danvez pennad',
  'djermon',
  'ébauche',
  'ébeuche',
  'ebòch',
  'édéntạ',
  'eginyn',
  'ẹ̀kúnrẹ́rẹ́',
  'en progreso',
  'entamu',
  'esboço',
  'esborrany',
  'esbòs',
  'esbozo',
  'ĝermo',
  'gumud',
  'ʻōmuku',
  'junj',
  'klado',
  'maramara',
  'mayele',
  'mbegu',
  'mrva',
  'na mulno',
  'nadabeigts rakstīņs',
  'nalta',
  'narcce',
  'pahýl',
  'pecietta',
  'phí',
  'pondok',
  'por mejoral',
  'potuʻi',
  'pungol',
  'qaralama',
  'rabisco',
  'rancangan',
  'rintisan',
  'saadjie',
  'saha',
  'sbozz',
  'sid',
  'síol',
  'şitil',
  'sjtumpke',
  'skizz',
  'skizze',
  'škrbina',
  'sơ khai',
  'spire',
  'stipula',
  'stob',
  'stobbe',
  'stock',
  'stompje',
  'stub',
  'stubben',
  'stubbi',
  'stubbur',
  'stump',
  'stumpen',
  'stycce',
  'suli',
  'taslak',
  'taslaq',
  'tunas',
  'turók',
  'tynkä',
  // 'u začetku',
  'vangovango',
  'vernuşte',
  'výhonok',
  'xinnoo',
  'zarodk',
  'zirriborroa',
  'επέκταση',
  'әҙерләмә',
  'заготовка',
  'керф',
  'кечдар',
  'клица',
  'къæртт',
  'кьурхь',
  'мәкалә төпчеге',
  'мъниче',
  'накід',
  'нєꙁаврьшєнъ члѣнъ',
  'никулец',
  'омоон',
  'стыржень',
  'хурд',
  'хӏадурунжо',
  'ესკიზი',
  'መዋቅር',
  'መዋቕር',
  'अपूर्णलेखः',
  'आधार',
  'ठुटो',
  'धाक्टें पान',
  'विस्तार',
  'অসম্পূর্ণ',
  'পোখালি',
  'સ્ટબ',
  'ଅଧାଗଢ଼ା',
  'குறுங்கட்டுரை',
  'మొలక',
  'ಎಲ್ಯ',
  'ಚುಟುಕು',
  'അപൂർണ്ണം',
  'අංකුරය',
  'โครง',
  'ཆ་མི་ཚང་བ',
  'អត្ថបទខ្លីមិនពេញលេញ',
  '토막글',
  '楔',
  '芻文',
]

// Արեւմտահայերէն Կաղապար:Անաւարտ
//     Հայերեն Կաղապար:Անավարտ
//     ייִדיש מוסטער:שטומף
//     עברית תבנית:קצרמר
//     ئۇيغۇرچە / Uyghurche قېلىپ:Stub
//     اردو سانچہ:نامکمل
//     الدارجة موضيل:زريعة
//     العربية قالب:بذرة
//     تۆرکجه شابلون:قارالاما
//     سنڌي سانچو:ڪچو
//     فارسی الگو:خرد
//     مازِرونی شابلون:پچوک بنویشته
//     مصرى قالب:تقاوى
//     پنجابی سانچہ:Stub
//     پښتو کينډۍ:نابشپړ
//     کوردی داڕێژە:کۆلکە
//     ܐܪܡܝܐ ܩܠܒܐ:Stub
//     ދިވެހިބަސް ފަންވަތް:Stub
//     अंगिका साँचा:आधार
//     अवधी खाँचा:Stub
//     कॉशुर / کٲشُر فرما:نامُکَمَل مَضموٗن
