module.exports = {
  // https://en.wikipedia.org/wiki/Category:Sex_and_sexuality_templates
  // (March 2020)
  'animal sexual behavior': 'Sexuality',
  bdsm: 'Sexuality',
  'birth control methods': 'Sexuality',
  'sexual ethics': 'Sexuality',
  'gender and sexual identities': 'Sexuality',
  'gender studies': 'Sexuality',
  'hormonal contraceptives': 'Sexuality',
  'human sexuality': 'Sexuality',
  'human sexuality/sandbox': 'Sexuality',
  'in defensum castitatis': 'Sexuality',
  incest: 'Sexuality',
  intersex: 'Sexuality',
  'intersex sidebar': 'Sexuality',
  'sex and the law': 'Sexuality',
  'sex manuals': 'Sexuality',
  masturbation: 'Sexuality',
  mindgeek: 'Sexuality',
  nudity: 'Sexuality',
  'sexual orientation': 'Sexuality',
  paraphilias: 'Sexuality',
  pedophilia: 'Sexuality',
  'sex positions': 'Sexuality',
  'post-orgasmic diseases': 'Sexuality',
  prostitution: 'Sexuality',
  'prostitution in canada': 'Sexuality',
  'prostitution in china': 'Sexuality',
  'prostitution in france': 'Sexuality',
  'prostitution in germany': 'Sexuality',
  'prostitution in india': 'Sexuality',
  'prostitution in japan': 'Sexuality',
  'prostitution in new zealand': 'Sexuality',
  'prostitution in sweden': 'Sexuality',
  'prostitution in thailand': 'Sexuality',
  'prostitution in the netherlands': 'Sexuality',
  "prostitution in the people's republic of china": 'Sexuality',
  'prostitution in the united kingdom': 'Sexuality',
  'prostitution in the united states': 'Sexuality',
  rape: 'Sexuality',
  'rape in india': 'Sexuality',
  'rape in the united states': 'Sexuality',
  rapefooter: 'Sexuality',
  sex: 'Sexuality',
  'sex (biology)': 'Sexuality',
  'sex (biology)/sandbox': 'Sexuality',
  'sex sidebar': 'Sexuality',
  'sex/sandbox': 'Sexuality',
  'sexual abuse': 'Sexuality',
  'sexual fetishism': 'Sexuality',
  'sexual revolution': 'Sexuality',
  'sidebar prostitution in france': 'Sexuality',
  'sidebar prostitution in the united kingdom': 'Sexuality',
  'adolescent sexuality by country': 'Sexuality',
  'sexual slang': 'Sexuality',
  'sexuality by country': 'Sexuality',
  'sexual urban legends': 'Sexuality',
  'wikipedia talk:wikiproject sexology and sexuality/talkheader': 'Sexuality',
  zoophilia: 'Sexuality',

  //
  'hentai-stub': 'Sexuality',
  'lgbt-sex-book-stub': 'Sexuality',
  'porn-book-stub': 'Sexuality',
  'porn-stub': 'Sexuality',
  'sex-book-stub': 'Sexuality',
  'sex-crime-stub': 'Sexuality',
  'sex-documentary-film-stub': 'Sexuality',
  'sex-stub': 'Sexuality',
  'sexuality-journal-stub': 'Sexuality',
  //
  '1890s-lgbt-novel-stub': 'Sexuality',
  '1900s-lgbt-novel-stub': 'Sexuality',
  '1920s-lgbt-novel-stub': 'Sexuality',
  '1930s-lgbt-novel-stub': 'Sexuality',
  '1940s-lgbt-novel-stub': 'Sexuality',
  '1950s-lgbt-novel-stub': 'Sexuality',
  '1960s-lgbt-novel-stub': 'Sexuality',
  '1970s-lgbt-novel-stub': 'Sexuality',
  '1980s-lgbt-novel-stub': 'Sexuality',
  '1990s-lgbt-novel-stub': 'Sexuality',
  '2000s-lgbt-novel-stub': 'Sexuality',
  '2010s-lgbt-novel-stub': 'Sexuality',
  'lgbt-activist-stub': 'Sexuality',
  'lgbt-bio-stub': 'Sexuality',
  'lgbt-book-stub': 'Sexuality',
  'lgbt-documentary-film-stub': 'Sexuality',
  'lgbt-drama-film-stub': 'Sexuality',
  'lgbt-film-stub': 'Sexuality',
  'lgbt-law-stub': 'Sexuality',
  'lgbt-mag-stub': 'Sexuality',
  'lgbt-newspaper-stub': 'Sexuality',
  'lgbt-novel-stub': 'Sexuality',
  'lgbt-org-stub': 'Sexuality',
  //
  'assisted reproductive technology': 'Sexuality',
  condoms: 'Sexuality',
  'female diseases of the pelvis and genitals': 'Sexuality',
  'human reproductive health': 'Sexuality',
  'human reproductive physiology': 'Sexuality',
  'male diseases of the pelvis and genitals': 'Sexuality',
  pregnancy: 'Sexuality',
  'std and sti': 'Sexuality',
  "women's health": 'Sexuality',

  'armalite ar-10 derivatives': 'Weapons',
  '4mmcaliber': 'Weapons',
  '7.62×39derivatives': 'Weapons',
  '30-30': 'Weapons',
  '30remington': 'Weapons',
  '32wslderivatives': 'Weapons',
  '.38 caliber': 'Weapons',
  '38scderivatives': 'Weapons',
  '222remderivatives': 'Weapons',
  '250-3000': 'Weapons',
  '284winchester': 'Weapons',
  '765borderivatives': 'Weapons',
  'advanced combat rifle prototypes': 'Weapons',
  aietc: 'Weapons',
  'antique firearms': 'Weapons',
  'api blowback firearms': 'Weapons',
  'armalite ar-16 derivatives': 'Weapons',
  'barrett firearms': 'Weapons',
  'beretta firearms': 'Weapons',
  'blow forward firearms': 'Weapons',
  'browning m1917 derivatives': 'Weapons',
  'bullpup firearms': 'Weapons',
  'caseless firearms': 'Weapons',
  'česká zbrojovka uherský brod': 'Weapons',
  "colt's manufacturing company": 'Weapons',
  'delayed blowback firearms': 'Weapons',
  'early firearms': 'Weapons',
  famae: 'Weapons',
  'fb firearms': 'Weapons',
  'firearm accessories mounting standards': 'Weapons',
  'fn herstal firearms': 'Weapons',
  'general purpose machine guns': 'Weapons',
  handloading: 'Weapons',
  'hk firearms': 'Weapons',
  imbel: 'Weapons',
  'imi iwi smallarms': 'Weapons',
  'improvised firearms': 'Weapons',
  'john browning': 'Weapons',
  'kalashnikov rifle': 'Weapons',
  'kel-tec firearms': 'Weapons',
  'komodo armament weapons': 'Weapons',
  'mauser firearms': 'Weapons',
  milkor: 'Weapons',
  'modern gatling guns': 'Weapons',
  'mossberg firearms': 'Weapons',
  'multiple barrel firearms': 'Weapons',
  'norwegian service rifles': 'Weapons',
  'personal defense weapons': 'Weapons',
  pindad: 'Weapons',
  'remington firearms': 'Weapons',
  'rpc fort weapons': 'Weapons',
  'ruger firearms': 'Weapons',
  savagefirearms: 'Weapons',
  'sig sauer firearms': 'Weapons',
  'smith & wesson': 'Weapons',
  'springfield armory firearms': 'Weapons',
  'sterling armaments company ltd': 'Weapons',
  'steyr mannlicher': 'Weapons',
  'swiss arms': 'Weapons',
  taurus: 'Weapons',
  'tbilisi aircraft manufacturing': 'Weapons',
  'walther firearms': 'Weapons',
  'weatherby cartridges firearms': 'Weapons',
  'winchester cartridges firearms': 'Weapons',
  'zastava firearms': 'Weapons',
  'ancient mechanical artillery and hand-held missile weapons': 'Weapons',
  'anti-tank rifles': 'Weapons',
  'artillery of the middle ages': 'Weapons',
  'bct subsystems': 'Weapons',
  britishempireweapons: 'Weapons',
  cannons: 'Weapons',
  'current french infantry weapons': 'Weapons',
  'current indian infantry weapons': 'Weapons',
  'usn early guided weapons': 'Weapons',
  'fcs subsystems': 'Weapons',
  'filipino weapons': 'Weapons',
  'history of the tank': 'Weapons',
  'imfdb name': 'Weapons',
  'imfdb title': 'Weapons',
  'indonesian weapons': 'Weapons',
  'japanese (samurai) weapons, armour and equipment': 'Weapons',
  'japanese swords': 'Weapons',
  'malaysian weapons': 'Weapons',
  'weapons of mass destruction': 'Weapons',
  'medieval armor components': 'Weapons',
  'medieval mechanical artillery and hand-held missile weapons': 'Weapons',
  'modern us infantry weapons': 'Weapons',
  modernausinfweaponsnav: 'Weapons',
  modernfininfweaponsnav: 'Weapons',
  modernukinfweaponsnav: 'Weapons',
  'notable swords': 'Weapons',
  'nuclear weapons tests of the united states': 'Weapons',
  'pole weapons': 'Weapons',
  'project kingfisher': 'Weapons',
  'royal navy torpedoes': 'Weapons',
  scud: 'Weapons',
  'station ix devices': 'Weapons',
  stryker: 'Weapons',
  'swords by region': 'Weapons',
  'us navy torpedoes': 'Weapons',
  'turkish army aircraft': 'Weapons',
  'turkish army infantry weapons': 'Weapons',
  'turkish army vehicles': 'Weapons',
  'types of armour': 'Weapons',
  'us military research rockets': 'Weapons',
  'us military rockets': 'Weapons',
  'usaf space vehicles': 'Weapons',
  valmetfirearmsnav: 'Weapons',
  'victorian era british naval weapons': 'Weapons',
  victorianerabritishweapons: 'Weapons',
  weapons: 'Weapons',
  'wwi tanks': 'Weapons',
  'missile navboxes': 'Weapons',
  'missile types': 'Weapons',
  'standard family of missiles': 'Weapons',
  'chinese missiles': 'Weapons',
  'dprk missiles': 'Weapons',
  'french nuclear missiles': 'Weapons',
  'gorgon missiles': 'Weapons',
  'indian missiles': 'Weapons',
  'indonesian missiles': 'Weapons',
  'iran missiles': 'Weapons',
  'missiles of pakistan': 'Weapons',
  'russian and soviet military designation sequences': 'Weapons',
  'russian and soviet missiles': 'Weapons',
  'russian and soviet surface-to-surface missiles': 'Weapons',
  'uk missiles': 'Weapons',
  'us army missiles': 'Weapons',
  'us missiles': 'Weapons',
  'usaf early missiles': 'Weapons',
  'usaf missiles': 'Weapons',
  'usn missiles': 'Weapons',
  'usn research missiles': 'Weapons',
  'v-weapons': 'Weapons',
  wwiiprototypeafvs: 'Weapons',
  'wwii us ships': 'Weapons',
  wwiiamericanafvs: 'Weapons',
  wwiiusguns: 'Weapons',
  wwiiusinfweaponsnav: 'Weapons',
  wwiiusnavalweapons: 'Weapons',
  'wwii australian ships': 'Weapons',
  'equipment of the belgian army in world war ii': 'Weapons',
  'ww1and2 british grenades': 'Weapons',
  'ww2 brit comm infantry guns': 'Weapons',
  'wwii british ships': 'Weapons',
  wwiibritishafvs: 'Weapons',
  wwiibritishaircraftweapons: 'Weapons',
  wwiibritishcommguns: 'Weapons',
  wwiibritishcommnavalweapons: 'Weapons',
  wwiibritishsoftveh: 'Weapons',
  wwiichineseheavyweapons: 'Weapons',
  wwiichineseinfantryweapons: 'Weapons',
  'wwii danish ships': 'Weapons',
  'wwii dutch ships': 'Weapons',
  'wwii finnish ships': 'Weapons',
  wwiifininfweaponsnav: 'Weapons',
  wwiifrenchguns: 'Weapons',
  coldwarfrenchafvs: 'Weapons',
  'wwii french ships': 'Weapons',
  wwiifrenchafvs: 'Weapons',
  wwiifrenchinfweapons: 'Weapons',
  wwiifrenchsoftveh: 'Weapons',
  wwiifrenchnavalweapons: 'Weapons',
  'german artillery of world war ii': 'Weapons',
  'mines of nazi germany during world war ii': 'Weapons',
  'ww2 german aerial weapons': 'Weapons',
  'wwii german ships': 'Weapons',
  wwiigermanafvs: 'Weapons',
  wwiigermaninfweapons: 'Weapons',
  'wwii greek ships': 'Weapons',
  'wwii italian ships': 'Weapons',
  wwiiitalianafvs: 'Weapons',
  wwiiitalianinfweapons: 'Weapons',
  wwiiitalianguns: 'Weapons',
  'imperial japanese army artillery': 'Weapons',
  'wwii japanese auxiliary ships': 'Weapons',
  'wwii japanese ships': 'Weapons',
  wwiijapanesenavalweapons: 'Weapons',
  'japanese wwii infantry weapons': 'Weapons',
  wwiijapaneseafvs: 'Weapons',
  wwiipolishafvs: 'Weapons',
  wwiipolishinfweapons: 'Weapons',
  'wwii polish ships': 'Weapons',
  'wwii romanian ships': 'Weapons',
  wwiiromanianafvs: 'Weapons',
  sovartygpw: 'Weapons',
  'soviet infantry weapons of world war ii': 'Weapons',
  'wwii soviet ships': 'Weapons',
  wwiisovaerosani: 'Weapons',
  wwiisovarttractors: 'Weapons',
  wwiisovexperimental: 'Weapons',
  wwiisovietafvs: 'Weapons',
  wwiisovietarmouredcars: 'Weapons',
  wwiisovietselfproparty: 'Weapons',
  wwiisovtanks: 'Weapons',
  'wwii swedish ships': 'Weapons',
  coldwarswedishafvs: 'Weapons',
  'weapons made in sweden 1914–1945': 'Weapons',
  'weapons of czechoslovakia': 'Weapons',
  'weapons of hungary': 'Weapons',
  wwiihungarianafvs: 'Weapons',
  wwiiswedishafvs: 'Weapons',
  'wwii yugoslav ships': 'Weapons',
  'austro-hungarian artillery of world war i': 'Weapons',
  'wwiaus-huninfweaponsequipment': 'Weapons',
  'austro-hungarian navy classes': 'Weapons',
  greatwarbritishnavalweapons: 'Weapons',
  'wwi british afvs': 'Weapons',
  'wwi british empire guns': 'Weapons',
  'wwi british empire small arms': 'Weapons',
  'wwi british ships': 'Weapons',
  wwifrenchguns: 'Weapons',
  wwifrenchinfweaponsnav: 'Weapons',
  'wwi french afvs': 'Weapons',
  'amphitrite-class submarine': 'Weapons',
  'bellone-class submarine': 'Weapons',
  'circé-class submarine (1907)': 'Weapons',
  'clorinde-class submarine': 'Weapons',
  'diane-class submarine (1916)': 'Weapons',
  'émeraude-class submarine (1906)': 'Weapons',
  'gustave zédé-class submarine': 'Weapons',
  'wwi french ships': 'Weapons',
  'wwi german ships': 'Weapons',
  wwigermanartillery: 'Weapons',
  wwigermaninfweaponsnav: 'Weapons',
  'wwi greek ships': 'Weapons',
  wwiitalianinfweapons: 'Weapons',
  'wwi italian ships': 'Weapons',
  wwiitalianguns: 'Weapons',
  'wwi japanese ships': 'Weapons',
  'wwi ottoman ships': 'Weapons',
  wwiottomaninfweaponsnav: 'Weapons',
  wwirussianarms: 'Weapons',
  'wwi russian ships': 'Weapons',
  'us wwi vehicles': 'Weapons',
  'wwi us ships': 'Weapons',
  wwiusguns: 'Weapons',
  wwiusinfweaponsnav: 'Weapons',
  'world war i aircraft of the central powers': 'Weapons',
  wwiusnavalweapons: 'Weapons',

  //
  'drug use': 'Drug-use',
  euphoriants: 'Drug-use',
  stimulants: 'Drug-use'
}
