module.exports = {
  'american football player': 'Person/Athlete',
  'australian politician': 'Person/Politician',
  'canadian politician': 'Person/Politician',
  'cape verde': 'Place',
  'cedar busway station': 'Place',
  'computer game': 'Product',
  'delhi metro': 'Place',
  'erie county, new york': 'Place',
  'football player': 'Person/Athlete',
  'gaelic footballer': 'Person/Athlete',
  'murder victim': 'Person',
  'new jersey': 'Place',
  'new orleans': 'Place',
  'new york City Subway': 'Place',
  'new york': 'Place',
  'new zealand': 'Place',
  'north carolina': 'Place',
  'northern ireland': 'Place',
  'season 2': 'CreativeWork',
  'season 3': 'CreativeWork',
  'season 4': 'CreativeWork',
  'season 5': 'CreativeWork',
  'sri lanka': 'Place',
  'the twilight zone': 'CreativeWork',
  'tv series': 'CreativeWork/TVShow',
  'uk parliament constituency': 'Place',
  'united kingdom': 'Place',
  'united states': 'Place',
  'video game': 'CreativeWork/VideoGame',
  academic: 'Person',
  actor: 'Person/Actor',
  actress: 'Person/Actor',
  alaska: 'Place',
  album: 'CreativeWork/Album',
  argentina: 'Place',
  arkansas: 'Place',
  artist: 'Person/Artist',
  athlete: 'Person/Athlete',
  australia: 'Place',
  author: 'Person',
  ballet: 'CreativeWork',
  band: 'Organization/MusicalGroup',
  barbados: 'Place',
  bishop: 'Person/ReligiousFigure',
  book: 'CreativeWork/Book',
  boxer: 'Person/Athlete',
  brazil: 'Place',
  businessman: 'Person',
  california: 'Place',
  canada: 'Place',
  candy: 'Product',
  chad: 'Place',
  character: 'FictionalCharacter',
  chicago: 'Place',
  // cocktail: 'Thing',
  colombia: 'Place',
  company: 'Organization/Company',
  composer: 'Person/Artist',
  connecticut: 'Place',
  cricketer: 'Person/Athlete',
  cyclist: 'Person',
  diplomat: 'Person',
  director: 'Person',
  dominica: 'Place',
  // drink: 'Thing',
  drummer: 'Person',
  edmonton: 'Place',
  footballer: 'Person/Athlete',
  france: 'Place',
  // game: 'Thing',
  georgia: 'Place',
  group: 'Organization',
  // horse: 'Thing',
  india: 'Place',
  israel: 'Place',
  japan: 'Place',
  journal: 'Organization',
  journalist: 'Person',
  judge: 'Person',
  magazine: 'CreativeWork',
  manhattan: 'Place',
  michigan: 'Place',
  miniseries: 'CreativeWork',
  minister: 'Person',
  movie: 'CreativeWork/Film',
  music: 'CreativeWork',
  musician: 'Person/Artist',
  newspaper: 'Organization/Company',
  nigeria: 'Place',
  novel: 'CreativeWork/Book',
  oklahoma: 'Place',
  ontario: 'Place',
  opera: 'CreativeWork',
  painter: 'Person/Artist',
  painting: 'CreativeWork',
  pennsylvania: 'Place',
  plant: 'Organism',
  play: 'CreativeWork/Play',
  poet: 'Person',
  politician: 'Person/Politician',
  portugal: 'Place',
  priest: 'Person',
  province: 'Place',
  rapper: 'Person/Artist',
  river: 'Place/BodyOfWater',
  series: 'CreativeWork',
  //  ship: 'Thing',
  singer: 'Person/Artist',
  single: 'CreativeWork',
  // software: 'Thing/Software',
  song: 'CreativeWork',
  soundtrack: 'CreativeWork',
  spain: 'Place',
  sudan: 'Place',
  texas: 'Place',
  //  train: 'Thing',
  uk: 'Place',
  va: 'Place',
  Virginia: 'Place',
  volcano: 'Place',
  washington: 'Place',
  wrestler: 'Person/Athlete',

  //March 29
  //learned works
  ep: 'CreativeWork',
  comics: 'CreativeWork',
  musical: 'CreativeWork',
  manga: 'CreativeWork',
  'star trek: the next generation': 'CreativeWork',
  'star trek: deep space nine': 'CreativeWork',
  'buffy the vampire slayer': 'CreativeWork',
  angel: 'CreativeWork',
  'the outer limits': 'CreativeWork',
  'star trek: voyager': 'CreativeWork',
  'short story': 'CreativeWork',
  seinfeld: 'CreativeWork',
  'star trek: enterprise': 'CreativeWork',
  poem: 'CreativeWork',
  tv: 'CreativeWork',
  'uk series': 'CreativeWork',
  'doctor who': 'CreativeWork',
  'david bowie song': 'CreativeWork',
  caravaggio: 'CreativeWork',
  'the beach boys song': 'CreativeWork',
  video: 'CreativeWork',
  'audio drama': 'CreativeWork',
  'babylon 5': 'CreativeWork',
  'madonna song': 'CreativeWork',
  'game show': 'CreativeWork/TVShow',
  'u.s. tv series': 'CreativeWork/TVShow',
  'uk tv series': 'CreativeWork/TVShow',
  'australian tv series': 'CreativeWork/TVShow',
  'u.s. game show': 'CreativeWork/TVShow',

  //learned events
  festival: 'Event',
  '25 m': 'Event',
  'world war ii': 'Event',
  conmebol: 'Event',
  'music festival': 'Event',
  'world war i': 'Event',

  //learned orgs
  am: 'Organization',
  fm: 'Organization',
  'american band': 'Organization/MusicalGroup',
  wehrmacht: 'Organization',
  'tv channel': 'Organization',
  'british band': 'Organization',
  organization: 'Organization',
  airline: 'Organization',
  publisher: 'Organization',
  'australian band': 'Organization/MusicalGroup',
  'canadian band': 'Organization/MusicalGroup',
  restaurant: 'Organization/Company',
  brand: 'Organization',
  'uk band': 'Organization/MusicalGroup',
  'record label': 'Organization',
  retailer: 'Organization/Company',
  'union army': 'Organization',
  store: 'Organization/Company',
  defunct: 'Organization',
  'tv network': 'Organization',
  'political party': 'Organization/PoliticalParty',
  'japanese band': 'Organization/MusicalGroup',
  'department store': 'Organization',
  'swedish band': 'Organization/MusicalGroup',

  //learned people
  'american football': 'Person',
  'ice hockey': 'Person',
  soccer: 'Person',
  'rugby league': 'Person',
  'rugby union': 'Person',
  'field hockey': 'Person',
  tennis: 'Person',
  writer: 'Person',
  vc: 'Person',
  'racing driver': 'Person',
  'british politician': 'Person/Politician',
  golfer: 'Person/Athlete',
  historian: 'Person/Academic',
  architect: 'Person',
  comedian: 'Person',
  cartoonist: 'Person/Artist',
  governor: 'Person/Politician',
  'british army officer': 'Person',
  general: 'Person',
  broadcaster: 'Person',
  engineer: 'Person',
  philosopher: 'Person/Academic',
  mathematician: 'Person/Academic',
  novelist: 'Person/Artist',
  physician: 'Person',
  swimmer: 'Person/Athlete',
  soldier: 'Person',
  photographer: 'Person/Artist',
  'royal navy officer': 'Person',
  producer: 'Person',
  theologian: 'Person/ReligiousFigure',
  lawyer: 'Person',
  playwright: 'Person/Artist',
  activist: 'Person',
  inventor: 'Person',
  astronomer: 'Person/Academic',
  'irish politician': 'Person/Politician',
  economist: 'Person/Academic',
  mayor: 'Person/Politician',
  moon: 'Place/SpaceLocation',
  country: 'Place/Country',

  // learned things
  // 'programming language': 'Thing/Software',
  genus: 'Organism',
  //  missile: 'Thing',
  'board game': 'Product',
  //  'new york city subway car': 'Thing',
  //  instrument: 'Thing',
  //  food: 'Thing',
  fish: 'Organism',
  bird: 'Organism',
  // 'operating system': 'Thing/Software',
  //  'file format': 'Thing',
  // 'computer virus': 'Thing/Software',
  'card game': 'Product',
  automobile: 'Product',
  //  rocket: 'Thing'
  // website: 'Thing/Software'
}
