module.exports = {
  'tv series': 'CreativeWork/TVShow',
  album: 'CreativeWork/Album',
  song: 'CreativeWork',
  film: 'CreativeWork/Film',
  politician: 'Person/Politician',
  footballer: 'Person/Athlete',
  musician: 'Person/Artist',
  Virginia: 'Place',
  band: 'Organization/MusicalGroup',
  'delhi metro': 'Place',
  'tv series': 'CreativeWork/TVShow',
  'uk parliament constituency': 'Place',
  'new jersey': 'Place',
  novel: 'CreativeWork/Book',
  portugal: 'Place',
  book: 'CreativeWork/Book',
  character: 'Thing/Character',
  company: 'Organization/Company',
  india: 'Place',
  game: 'Thing',
  'video game': 'Thing/Product',
  'computer game': 'Thing/Product',
  'season 2': 'CreativeWork',
  california: 'Place',
  athlete: 'Person/Athlete',
  soundtrack: 'CreativeWork',
  cricketer: 'Person/Athlete',
  horse: 'Thing',
  newspaper: 'Organization/Company',
  wrestler: 'Person/Athlete',
  connecticut: 'Place',
  uk: 'Place',
  software: 'Thing/Software',
  canada: 'Place',
  journalist: 'Person',
  bishop: 'Person',
  train: 'Thing',
  '2006 film': 'CreativeWork',
  'season 3': 'CreativeWork',
  singer: 'Person/Artist',
  actor: 'Person/Actor',
  artist: 'Person/Artist',
  volcano: 'Place',
  'season 4': 'CreativeWork',
  'united states': 'Place',
  'united kingdom': 'Place',
  movie: 'CreativeWork/Film',
  judge: 'Person',
  'football player': 'Person/Athlete',
  'erie county, new york': 'Place',
  arkansas: 'Place',
  oklahoma: 'Place',
  single: 'CreativeWork',
  series: 'CreativeWork',
  nigeria: 'Place',
  pennsylvania: 'Place',
  magazine: 'CreativeWork',
  opera: 'CreativeWork',
  'murder victim': 'Person',
  australia: 'Place',
  'The Twilight Zone': 'CreativeWork',
  music: 'CreativeWork',
  georgia: 'Place',
  poet: 'Person',
  va: 'Place',
  play: 'CreativeWork',
  actress: 'Person/Actor',
  album: 'CreativeWork/Album',
  ship: 'Thing',
  spain: 'Place',
  boxer: 'Person/Athlete',
  author: 'Person',
  painter: 'Person/Artist',
  michigan: 'Place',
  'tv series': 'CreativeWork',
  sudan: 'Place',
  chad: 'Place',
  brazil: 'Place',
  france: 'Place',
  director: 'Person',
  alaska: 'Place',
  priest: 'Person',
  minister: 'Person',
  province: 'Place',
  'season 5': 'CreativeWork',
  barbados: 'Place',
  diplomat: 'Person',
  japan: 'Place',
  'new york': 'Place',
  ontario: 'Place',
  painting: 'Thing',
  cocktail: 'Thing',
  'cedar busway station': 'Place',
  cyclist: 'Person',
  book: 'CreativeWork',
  'cape verde': 'Place',
  river: 'Place/BodyOfWater',
  'australian politician': 'Person/Politician',
  businessman: 'Person',
  'canadian politician': 'Person/Politician',
  academic: 'Person',
  dominica: 'Place',
  journal: 'Organization',
  plant: 'Thing',
  'north carolina': 'Place',
  'new york City Subway': 'Place',
  candy: 'Thing',
  group: 'Organization',
  chicago: 'Place',
  argentina: 'Place',
  manhattan: 'Place',
  'new orleans': 'Place',
  song: 'CreativeWork',
  rapper: 'Person/Artist',
  drink: 'Thing',
  composer: 'Person/Artist',
  texas: 'Place',
  'new zealand': 'Place',
  miniseries: 'CreativeWork',
  'northern ireland': 'Place',
  drummer: 'Person',
  'sri lanka': 'Place',
  'gaelic footballer': 'Person/Athlete',
  ballet: 'CreativeWork',
  'american football player': 'Person/Athlete',
  colombia: 'Place',
  israel: 'Place',
  washington: 'Place',
  edmonton: 'Place',
  plant: 'Thing/Organism'
}
