export default {
  name: 'HockeyPlayer',
  //
  children: {},
  //
  categories: {
    mapping: [
      'stanley cup champions',
      'anaheim ducks players',
      'arizona coyotes players',
      'atlanta flames players',
      'atlanta thrashers players',
      'boston bruins players',
      'brooklyn americans players',
      'buffalo sabres players',
      'calgary flames players',
      'california golden seals players',
      'carolina hurricanes players',
      'chicago blackhawks players',
      'cleveland barons (nhl) players',
      'colorado avalanche players',
      'colorado rockies (nhl) players',
      'columbus blue jackets players',
      'dallas stars players',
      'detroit cougars players',
      'detroit falcons players',
      'detroit red wings players',
      'edmonton oilers players',
      'florida panthers players',
      'hamilton tigers (ice hockey) players',
      'hartford whalers players',
      'kansas city scouts players',
      'los angeles kings players',
      'mighty ducks of anaheim players',
      'minnesota north stars players',
      'minnesota wild players',
      'montreal canadiens players',
      'montreal maroons players',
      'montreal wanderers (nhl) players',
      'nashville predators players',
      'new jersey devils players',
      'new york americans players',
      'new york islanders players',
      'new york rangers players',
      'oakland seals players',
      'ottawa senators (1917) players',
      'ottawa senators players',
      'philadelphia flyers players',
      'philadelphia quakers (nhl) players',
      'phoenix coyotes players',
      'pittsburgh penguins players',
      'pittsburgh pirates (nhl) players',
      'quebec bulldogs players',
      'quebec nordiques players',
      'san jose sharks players',
      'seattle kraken players',
      'st. louis blues players',
      'st. louis eagles players',
      'tampa bay lightning players',
      'toronto arenas players',
      'toronto maple leafs players',
      'toronto st. pats players',
      'vancouver canucks players',
      'vegas golden knights players',
      'washington capitals players',
      'winnipeg jets (1979–1996) players',
      'winnipeg jets players',
    ],
    patterns: [/ice hockey players/],
  },
  //
  descriptions: {
    patterns: [],
  },
  //
  infoboxes: {
    mapping: ['ice_hockey_player', 'hockey_team_player'],
    patterns: [],
  },
  //
  sections: {
    mapping: [],
    patterns: [],
  },
  //
  templates: {
    mapping: [],
    patterns: [],
  },
  //
  titles: {
    mapping: [],
    patterns: [],
  },
}
