// from ./plugins/classify/infobox, April 15 2020
// https://en.wikipedia.org/wiki/Category:People_and_person_infobox_templates
module.exports = {
  actor: true,
  adult_biography: true,
  afl_biography: true,
  alpine_ski_racer: true,
  archbishop: true,
  architect: true,
  artist: true,
  athlete: true,
  baseball_biography: true,
  basketball_biography: true,
  boxer: true,
  canadianmp: true,
  cfl_player: true,
  chef: true,
  chess_player: true,
  christian_leader: true,
  college_coach: true,
  college_football_player: true,
  comedian: true,
  comics_creator: true,
  cricketer: true,
  criminal: true,
  cyclist: true,
  economist: true,
  engineer: true,
  fashion_designer: true,
  field_hockey_player: true,
  figure_skater: true,
  football_biography: true,
  gaa_player: true,
  golfer: true,
  governor: true,
  gridiron_football_person: true,
  gymnast: true,
  handball_biography: true,
  hindu_leader: true,
  horseracing_personality: true,
  ice_hockey_player: true,
  indian_politician: true,
  judge: true,
  lacrosse_player: true,
  martial_artist: true,
  mass_murderer: true,
  medical_person: true,
  military_person: true,
  minister: true,
  mlb_player: true,
  model: true,
  monarch: true,
  mp: true,
  nascar_driver: true,
  nba_biography: true,
  nfl_biography: true,
  nfl_player: true,
  officeholder: true,
  person: true,
  philosopher: true,
  police_officer: true,
  politician: true,
  'politician_(general)': true,
  presenter: true,
  president: true,
  professional_wrestler: true,
  racing_driver: true,
  religious_biography: true,
  roman_emperor: true,
  royalty: true,
  rugby_biography: true,
  rugby_league_biography: true,
  saint: true,
  scholar: true,
  scientist: true,
  skier: true,
  sportsperson: true,
  squash_player: true,
  state_representative: true,
  state_senator: true,
  swimmer: true,
  tennis_biography: true,
  volleyball_biography: true,
  volleyball_player: true,
  wrc_driver: true,
  writer: true,
  'hockey team player': true,
  'snooker player': true,
  bishop: true,
  'football biography': true,
  'military person': true,
  'baseball biography': true,
  'ice hockey player': true,
  'nfl player': true,
  'christian leader': true,
  congressman: true,
  'basketball biography': true,
  'comics creator': true,
  'professional wrestler': true,
  'college coach': true,
  'tennis biography': true,
  'afl biography': true,
  'nfl biography': true,
  'rugby biography': true,
  'rugby league biography': true,
  'prime minister': true,
  'nba biography': true,
  'figure skater': true,
  'f1 driver': true,
  'gridiron football person': true,
  'indian politician': true,
  'racing driver': true,
  'martial artist': true,
  'chinese-language singer and actor': true,
  astronaut: true,
  senator: true,
  'nascar driver': true,
  'adult biography': true,
  'state representative': true,
  'state senator': true,
  'coa wide': true,
  'religious biography': true,
  'chess player': true,
  'pageant titleholder': true,
  'gaa player': true,
  'us cabinet official': true
}
