name: Release

on:
  release:
    types: [created]
# on:
#   push:
#     branches:
#       - master

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    
    env:
      CI: true
    
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with: 
          node-version: '24.x'
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - name: install
        run: |
          pnpm install --frozen-lockfile

      - name: static checks
        run: |
          pnpm run lint
          pnpm run check
          pnpm run test:types

      - name: build
        run: |
          pnpm run build:all

      - name: test
        run: |
          pnpm run testb
          pnpm run test:plugins:built
          pnpm run test:fetch

      # And finally... publish it!  Note that we create the .npmrc file
      # "just in time" so that `npm publish` can get the auth token from the
      # environment
      - name: publish
        run: |
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
          npm publish --provenance
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
