module.exports = {
  actor: 'Person', //1
  adult_biography: '', //2
  afl_biography: '', //7
  aircraft_accident: '', //2
  aircraft_begin: '', //24
  aircraft_engine: '', //2
  aircraft_occurrence: '', //5
  aircraft_type: '', //21
  airline: '', //9
  airliner_accident: '', //3
  airport: '', //20
  album: '', //466
  'album/color': '', //1
  alpine_ski_racer: 'Person/Athlete', //2
  amusement_park: '', //4
  ancient_site: '', //14
  'animanga/footer': '', //21
  'animanga/game': '', //2
  'animanga/header': '', //21
  'animanga/print': '', //12
  'animanga/video': '', //23
  antipope: '', //1
  archbishop: 'Person', //1
  architect: 'Person', //9
  artifact: '', //1
  artist: 'Person/Artist', //42
  artist_discography: '', //9
  artwork: '', //14
  athlete: '', //6
  athletics_championships: '', //6
  australian_electorate: '', //3
  australian_place: '', //18
  automobile: '', //8
  award: '', //30
  badminton_event: '', //2
  baseball_biography: '', //64
  basketball_biography: '', //17
  beauty_pageant: '', //4
  beverage: '', //7
  bilateral_relations: '', //2
  biodatabase: '', //2
  bishopric: '', //3
  body_of_water: '', //7
  book: '', //130
  book_series: '', //4
  boxer: 'Person/Athlete', //5
  boxingmatch: '', //2
  brand: '', //1
  bridge: '', //5
  broadcast: '', //10
  broadcasting_network: '', //4
  building: '', //29
  bus_transit: '', //5
  canadianmp: 'Person/Politician', //18
  canton: '', //1
  cardinalstyles: '', //2
  casino: '', //1
  cave: '', //2
  cbb_team: '', //1
  cemetery: '', //3
  cfl_player: 'Person/Athlete', //2
  character: '', //12
  chef: 'Person', //6
  chess_player: 'Person', //2
  chinese: '', //6
  'chinese-language_singer_and_actor': '', //5
  choir: '', //1
  christian_denomination: '', //6
  christian_leader: 'Person', //17
  church: '', //10
  civil_conflict: '', //3
  coa_wide: '', //3
  coin: '', //4
  college: '', //2
  college_coach: 'Person', //18
  college_football_player: 'Person', //7
  college_ice_hockey_team: '', //1
  college_soccer_team: '', //3
  comedian: 'Person', //3
  comic_book_title: '', //9
  comic_strip: '', //1
  comics_character: '', //13
  comics_creator: '', //10
  comics_set_index: '', //1
  comics_story_arc: '', //1
  company: '', //150
  computer_hardware_bus: '', //1
  computer_virus: '', //1
  concert_tour: '', //8
  constellation: '', //5
  country_at_games: '', //6
  court_case: '', //8
  cpu: '', //1
  cricket_ground: '', //2
  cricket_team: '', //1
  cricketer: 'Person', //43
  criminal: 'Person', //8
  cyclist: 'Person/Athlete', //8
  'd&d_creature': '', //3
  dam: '', //4
  data_structure: '', //1
  deity: '', //5
  disease: '', //2
  doctor_who_episode: '', //3
  'dot-com_company': '', //3
  drug_class: '', //1
  earthquake: '', //2
  economist: 'Person', //4
  economy: '', //4
  election: '', //19
  electric_vehicle: '', //1
  engineer: 'Person', //2
  enzyme: '', //19
  ethnic_group: '', //16
  event: '', //2
  exchange: '', //2
  fashion_designer: 'Person', //2
  feature_on_mars: '', //1
  field_hockey: '', //18
  field_hockey_player: 'Person', //8
  figure_skater: 'Person', //3
  fila_wrestling_event: '', //1
  file_format: '', //3
  film: '', //183
  film_awards: '', //1
  film_festival: '', //2
  food: '', //3
  football_biography: '', //324
  football_club: '', //42
  football_club_season: '', //13
  football_country_season: '', //5
  football_league: '', //4
  football_league_season: '', //17
  football_match: '', //10
  football_tournament_season: '', //4
  former_country: '', //14
  former_subdivision: '', //3
  french_commune: '', //6
  french_constituency: '', //20
  'g.i._joe_character': '', //1
  gaa_club: '', //2
  gaa_player: 'Person', //15
  game: '', //3
  games: '', //3
  gene: '', //3
  german_location: '', //6
  given_name: '', //9
  golf_facility: '', //2
  golfer: '', //9
  government_agency: '', //7
  government_cabinet: '', //7
  governor: 'Person/Politician', //5
  gpu: '', //1
  grappling_hold: '', //1
  gridiron_football_person: '', //11
  gymnast: 'Person/Athlete', //2
  handball_biography: '', //8
  hindu_leader: 'Person', //1
  historic_site: '', //3
  historical_era: '', //1
  holiday: '', //5
  hollywood_cartoon: '', //4
  horse: '', //1
  horseraces: '', //8
  horseracing_personality: 'Person', //2
  hospital: '', //14
  hotel: '', //3
  'hurling_all-ireland': '', //2
  hurricane: '', //1
  ice_hockey_player: 'Person/Athlete', //15
  indian_politician: 'Person/Politician', //1
  individual_snooker_tournament: '', //6
  information_appliance: '', //6
  instrument: '', //3
  islands: '', //32
  israel_village: '', //2
  italian_comune: '', //1
  journal: '', //23
  judge: 'Person', //8
  judo_technique: '', //2
  korean_name: '', //18
  laboratory: '', //1
  lacrosse_player: 'Person/Athlete', //6
  lake: '', //10
  language: '', //24
  language_family: '', //5
  launch_pad: '', //1
  law_enforcement_agency: '', //1
  legislation: '', //6
  legislative_term: '', //1
  legislature: '', //3
  lgbt_rights: '', //3
  library: '', //9
  ligament: '', //1
  little_league_world_series: '', //5
  magazine: '', //15
  martial_art: '', //2
  martial_artist: 'Person/Athlete', //13
  mass_murderer: 'Person', //1
  medical_condition: '', //31
  'medical_condition_(new)': '', //6
  medical_person: 'Person', //5
  military_conflict: '', //27
  military_installation: '', //1
  military_memorial: '', //2
  military_person: 'Person', //60
  military_structure: '', //15
  military_unit: '', //33
  mineral: '', //5
  minister: 'Person', //3
  mla: '', //1
  mlb_player: 'Person', //8
  mobile_phone: '', //3
  model: 'Person', //2
  monarch: 'Person', //23
  monument: '', //1
  motorcycle: '', //5
  mountain: '', //59
  mountain_pass: '', //1
  mountain_range: '', //13
  mp: '', //13
  museum: '', //13
  music_festival: '', //5
  music_genre: '', //5
  musical: '', //3
  musical_artist: 'Person/Artist', //226
  musical_composition: '', //7
  nascar_driver: 'Person', //3
  nascar_race_report: '', //1
  national_military: '', //4
  nba_biography: 'Person/Athlete', //4
  nba_season: '', //6
  ncaa_baseball_conference_tournament: '', //6
  ncaa_football_school: '', //4
  ncaa_football_single_game: '', //1
  ncaa_team_season: '', //17
  neighborhood_portland_or: '', //3
  network: '', //3
  networking_protocol: '', //1
  newspaper: '', //18
  nfl_biography: 'Person/Athlete', //7
  nfl_draft: '', //2
  nfl_player: '', //36
  nfl_season: '', //27
  nfl_single_game: '', //1
  nobility: '', //5
  non_test_cricket_team: '', //4
  'non-profit': '', //6
  nrhp: '', //144
  nycs: '', //7
  officeholder: '', //133
  official_post: '', //1
  oil_field: '', //1
  opera: '', //3
  organization: '', //41
  os: '', //1
  painting: '', //2
  pandemic: '', //2
  park: '', //15
  pba_draft: '', //3
  person: 'Person', //441
  philosopher: 'Person', //16
  physical_quantity: '', //1
  police_officer: 'Person', //2
  political_party: '', //25
  politician: 'Person/Politician', //34
  'politician_(general)': 'Person/Politician', //2
  port: '', //5
  power_station: '', //3
  prepared_food: '', //12
  presenter: 'Person', //4
  president: 'Person/Politician', //1
  prison: '', //4
  professional_wrestler: 'Person/Athlete', //9
  programming_language: '', //6
  project: '', //1
  protein_family: '', //2
  province_or_territory_of_canada: '', //1
  public_transit: '', //1
  publisher: '', //3
  racing_driver: 'Person', //4
  radio_show: '', //3
  radio_station: '', //25
  rail: '', //4
  rail_line: '', //7
  rail_service: '', //6
  rdt: '', //2
  reality_music_competition: '', //1
  record_label: '', //7
  recurring_event: '', //3
  region_symbols: '', //1
  religious_biography: 'Person', //9
  religious_building: '', //9
  religious_text: '', //1
  restaurant: '', //4
  river: '', //16
  road: '', //41
  road_small: '', //14
  rocket: '', //3
  rockunit: '', //3
  roman_emperor: 'Person/Politician', //2
  royal_house: '', //1
  royalty: '', //77
  rugby_biography: 'Person/Athlete', //12
  rugby_league_biography: '', //24
  rugby_league_club: '', //5
  rugby_league_representative_team: '', //1
  rugby_team: '', //11
  russian_inhabited_locality: '', //1
  russian_town: '', //4
  'russian_urban-type_settlement': '', //2
  saint: 'Person', //14
  scholar: 'Person', //2
  school: '', //95
  school_district: '', //10
  scientist: 'Person/Scientist', //84
  scotland_council_area: '', //2
  scotus_case: '', //6
  sea: '', //3
  settlement: 'Place', //642
  sheep_breed: '', //1
  ship_begin: '', //84
  ship_career: '', //141
  ship_characteristics: '', //86
  ship_class_overview: '', //25
  ship_image: '', //84
  shopping_mall: '', //9
  single: '', //160
  skier: 'Person/Athlete', //14
  soap_character: '', //126
  software: '', //25
  software_license: '', //1
  song: '', //30
  song_contest: '', //3
  song_contest_entry: '', //12
  south_african_subplace_2011: '', //1
  spaceflight: '', //17
  'spaceflight/dock': '', //17
  'spaceflight/ip': '', //19
  sport: '', //2
  sport_governing_body: '', //3
  sports_league: '', //7
  sports_season: '', //3
  sportsperson: 'Person', //45
  squash_player: 'Person/Athlete', //1
  stadium: '', //14
  state: '', //1
  state_representative: '', //10
  state_senator: '', //5
  station: '', //40
  street: '', //1
  subdivision_type: '', //1
  summit: '', //2
  swimmer: 'Person/Athlete', //14
  swiss_town: '', //36
  symptom: '', //2
  synthesizer: '', //1
  television: '', //94
  television_channel: '', //1
  television_episode: '', //26
  television_season: '', //18
  temple: '', //2
  tennis_biography: 'Person/Athlete', //5
  tennis_event: '', //3
  tennis_grand_slam_events: '', //2
  theatre: '', //1
  thoroughbred_racehorse: '', //7
  tour_rugby: '', //1
  town_at: '', //1
  train: '', //2
  treaty: '', //2
  tv_channel: '', //12
  'u.s._cabinet': '', //3
  'u.s._legislation': '', //3
  'u.s._metropolitan_area': '', //1
  'u.s._state': '', //3
  'u.s._state_symbols': '', //4
  uk_constituency: '', //1
  uk_disused_station: '', //8
  uk_legislation: '', //6
  uk_place: '', //22
  uk_school: '', //26
  ukrainian_raion: '', //1
  unesco_world_heritage_site: '', //3
  unit: '', //4
  united_states_federal_proposed_legislation: '', //1
  university: '', //44
  university_of_notre_dame_residence_hall: '', //1
  v8_supercar_team: '', //3
  venue: '', //6
  vg: '', //3
  vg_series: '', //4
  video_game: '', //81
  volleyball_biography: 'Person/Athlete', //1
  volleyball_player: 'Person/Athlete', //4
  waterfall: '', //4
  weapon: '', //15
  website: '', //5
  windmill: '', //1
  worldscouting: '', //2
  wrc_driver: 'Person', //1
  wrestling_event: '', //8
  wrestling_promotion: '', //1
  writer: 'Person', //69
  writing_system: '', //4
  zoo: '' //3
}
