module.exports = {
  actor: 'Person', //1
  adult_biography: 'Person', //2
  afl_biography: 'Person', //7
  aircraft_accident: 'Event/Disaster', //2
  aircraft_begin: 'Thing', //24
  aircraft_engine: 'Thing', //2
  aircraft_occurrence: '', //5
  aircraft_type: 'Thing', //21
  airline: 'Organization', //9
  airliner_accident: 'Event/Disaster', //3
  airport: 'Place', //20
  album: 'CreativeWork/Album', //466
  'album/color': '', //1
  alpine_ski_racer: 'Person/Athlete', //2
  amusement_park: 'Place', //4
  ancient_site: 'Place', //14
  'animanga/footer': '', //21
  'animanga/game': '', //2
  'animanga/header': '', //21
  'animanga/print': '', //12
  'animanga/video': '', //23
  antipope: '', //1
  archbishop: 'Person', //1
  architect: 'Person', //9
  artifact: 'Thing', //1
  artist: 'Person/Artist', //42
  artist_discography: '', //9
  artwork: 'CreativeWork', //14
  athlete: 'Person/Athlete', //6
  athletics_championships: 'Event/SportsEvent', //6
  australian_electorate: '', //3
  australian_place: 'Place', //18
  automobile: 'Thing/Product', //8
  award: '', //30
  badminton_event: 'Event/SportsEvent', //2
  baseball_biography: 'Person/Athlete', //64
  basketball_biography: 'Person/Athlete', //17
  beauty_pageant: 'Event', //4
  beverage: 'Thing/Product', //7
  bilateral_relations: '', //2
  biodatabase: '', //2
  bishopric: '', //3
  body_of_water: 'Place/BodyOfWater', //7
  book: 'CreativeWork/Book', //130
  book_series: 'CreativeWork', //4
  boxer: 'Person/Athlete', //5
  boxingmatch: 'Event/SportsEvent', //2
  brand: '', //1
  bridge: 'Place/Structure', //5
  broadcast: 'CreativeWork', //10
  broadcasting_network: 'Organization', //4
  building: 'Place/Structure', //29
  bus_transit: '', //5
  canadianmp: 'Person/Politician', //18
  canton: '', //1
  cardinalstyles: '', //2
  casino: 'Place', //1
  cave: '', //2
  cbb_team: 'Organization', //1
  cemetery: 'Place', //3
  cfl_player: 'Person/Athlete', //2
  character: 'Thing/Character', //12
  chef: 'Person', //6
  chess_player: 'Person', //2
  chinese: '', //6
  'chinese-language_singer_and_actor': '', //5
  choir: 'Organization', //1
  christian_denomination: '', //6
  christian_leader: 'Person', //17
  church: 'Place', //10
  civil_conflict: 'Event', //3
  coa_wide: '', //3
  coin: '', //4
  college: 'Organization', //2
  college_coach: 'Person', //18
  college_football_player: 'Person', //7
  college_ice_hockey_team: 'Organization/SportsTeam', //1
  college_soccer_team: 'Organization/SportsTeam', //3
  comedian: 'Person', //3
  comic_book_title: 'CreativeWork', //9
  comic_strip: 'CreativeWork', //1
  comics_character: 'Thing/Character', //13
  comics_creator: 'Person', //10
  comics_set_index: '', //1
  comics_story_arc: '', //1
  company: 'Organization', //150
  computer_hardware_bus: 'Thing', //1
  computer_virus: 'Thing/Software', //1
  concert_tour: 'Event', //8
  constellation: '', //5
  country_at_games: '', //6
  court_case: 'Event', //8
  cpu: 'Thing/Product', //1
  cricket_ground: 'Place', //2
  cricket_team: 'Organization/SportsTeam', //1
  cricketer: 'Person/Athlete', //43
  criminal: 'Person', //8
  cyclist: 'Person/Athlete', //8
  'd&d_creature': '', //3
  dam: 'Place', //4
  data_structure: '', //1
  deity: '', //5
  disease: '', //2
  doctor_who_episode: 'CreativeWork', //3
  'dot-com_company': 'Organization', //3
  drug_class: '', //1
  earthquake: 'Event/Disaster', //2
  economist: 'Person', //4
  economy: '', //4
  election: 'Event/Election', //19
  electric_vehicle: 'Thing/Product', //1
  engineer: 'Person', //2
  enzyme: 'Thing', //19
  ethnic_group: '', //16
  event: 'Event', //2
  exchange: '', //2
  fashion_designer: 'Person', //2
  feature_on_mars: 'Place', //1
  field_hockey: '', //18
  field_hockey_player: 'Person/Athlete', //8
  figure_skater: 'Person/Athlete', //3
  fila_wrestling_event: 'Event/SportsEvent', //1
  file_format: 'Thing', //3
  film: 'CreativeWork/Film', //183
  film_awards: 'Organization', //1
  film_festival: 'Organization', //2
  food: 'Thing', //3
  football_biography: 'Person', //324
  football_club: 'Organization/SportsTeam', //42
  football_club_season: 'Event/SportsEvent', //13
  football_country_season: 'Event/SportsEvent', //5
  football_league: 'Organization', //4
  football_league_season: 'Event/SportsEvent', //17
  football_match: 'Event/SportsEvent', //10
  football_tournament_season: 'Event/SportsEvent', //4
  former_country: 'Place', //14
  former_subdivision: 'Place', //3
  french_commune: 'Place', //6
  french_constituency: '', //20
  'g.i._joe_character': '', //1
  gaa_club: 'Organization', //2
  gaa_player: 'Person/Athlete', //15
  game: 'Thing', //3
  games: '', //3
  gene: 'Thing', //3
  german_location: 'Place', //6
  given_name: '', //9
  golf_facility: 'Place', //2
  golfer: 'Person/Athlete', //9
  government_agency: 'Organization', //7
  government_cabinet: 'Organization', //7
  governor: 'Person/Politician', //5
  gpu: 'Thing/Product', //1
  grappling_hold: '', //1
  gridiron_football_person: 'Person', //11
  gymnast: 'Person/Athlete', //2
  handball_biography: 'Person', //8
  hindu_leader: 'Person', //1
  historic_site: 'Place', //3
  historical_era: 'Event', //1
  holiday: 'Event', //5
  hollywood_cartoon: 'CreativeWork', //4
  horse: '', //1
  horseraces: 'Event', //8
  horseracing_personality: 'Person', //2
  hospital: 'Place', //14
  hotel: 'Place', //3
  'hurling_all-ireland': '', //2
  hurricane: 'Event/Disaster', //1
  ice_hockey_player: 'Person/Athlete', //15
  indian_politician: 'Person/Politician', //1
  individual_snooker_tournament: 'Event', //6
  information_appliance: 'Thing', //6
  instrument: 'Thing', //3
  islands: 'Place', //32
  israel_village: 'Place', //2
  italian_comune: 'Place', //1
  journal: 'Organization', //23
  judge: 'Person', //8
  judo_technique: 'Thing', //2
  korean_name: '', //18
  laboratory: 'Organization', //1
  lacrosse_player: 'Person/Athlete', //6
  lake: 'Place/BodyOfWater', //10
  language: '', //24
  language_family: '', //5
  launch_pad: 'Place', //1
  law_enforcement_agency: 'Organization', //1
  legislation: '', //6
  legislative_term: 'Event', //1
  legislature: 'Organization', //3
  lgbt_rights: '', //3
  library: 'Organization', //9
  ligament: 'Thing', //1
  little_league_world_series: 'Event/SportsEvent', //5
  magazine: 'CreativeWork', //15
  martial_art: 'Thing', //2
  martial_artist: 'Person/Athlete', //13
  mass_murderer: 'Person', //1
  medical_condition: 'Thing', //31
  'medical_condition_(new)': '', //6
  medical_person: 'Person', //5
  military_conflict: 'Event/War', //27
  military_installation: '', //1
  military_memorial: 'Place', //2
  military_person: 'Person', //60
  military_structure: 'Place', //15
  military_unit: 'Organization', //33
  mineral: 'Thing', //5
  minister: 'Person', //3
  mla: '', //1
  mlb_player: 'Person/Athlete', //8
  mobile_phone: 'Thing/Product', //3
  model: 'Person', //2
  monarch: 'Person', //23
  monument: 'Place', //1
  motorcycle: 'Thing/Product', //5
  mountain: 'Place', //59
  mountain_pass: 'Place', //1
  mountain_range: 'Place', //13
  mp: 'Person/Politician', //13
  museum: 'Place', //13
  music_festival: 'Event', //5
  music_genre: 'Thing', //5
  musical: 'CreativeWork', //3
  musical_artist: 'Organization/MusicalGroup', //226
  musical_composition: 'CreativeWork', //7
  nascar_driver: 'Person', //3
  nascar_race_report: '', //1
  national_military: 'Organization', //4
  nba_biography: 'Person/Athlete', //4
  nba_season: 'Event/SportsEvent', //6
  ncaa_baseball_conference_tournament: 'Event/SportsEvent', //6
  ncaa_football_school: 'Organization', //4
  ncaa_football_single_game: 'Event/SportsEvent', //1
  ncaa_team_season: 'Event/SportsEvent', //17
  neighborhood_portland_or: 'Place', //3
  network: 'Thing', //3
  networking_protocol: 'Thing', //1
  newspaper: 'Organization', //18
  nfl_biography: 'Person/Athlete', //7
  nfl_draft: 'Event', //2
  nfl_player: 'Person/Athlete', //36
  nfl_season: 'Event/SportsEvent', //27
  nfl_single_game: 'Event/SportsEvent', //1
  nobility: 'Organization', //5
  non_test_cricket_team: 'Organization/SportsTeam', //4
  'non-profit': 'SportsTeam', //6
  nrhp: '', //144
  nycs: '', //7
  officeholder: 'Person', //133
  official_post: '', //1
  oil_field: 'Place', //1
  opera: 'CreativeWork', //3
  organization: 'Organization', //41
  os: 'Thing', //1
  painting: 'CreativeWork', //2
  pandemic: 'Event/Disaster', //2
  park: 'Place', //15
  pba_draft: 'Event', //3
  person: 'Person', //441
  philosopher: 'Person', //16
  physical_quantity: '', //1
  police_officer: 'Person', //2
  political_party: 'Organization', //25
  politician: 'Person/Politician', //34
  'politician_(general)': 'Person/Politician', //2
  port: '', //5
  power_station: 'Place/Structure', //3
  prepared_food: 'Thing', //12
  presenter: 'Person', //4
  president: 'Person/Politician', //1
  prison: 'Place', //4
  professional_wrestler: 'Person/Athlete', //9
  programming_language: 'Thing', //6
  project: '', //1
  protein_family: 'Thing', //2
  province_or_territory_of_canada: 'Place', //1
  public_transit: 'Organization', //1
  publisher: 'Organization', //3
  racing_driver: 'Person', //4
  radio_show: 'CreativeWork', //3
  radio_station: 'Organization', //25
  rail: '', //4
  rail_line: 'Organization', //7
  rail_service: 'Organization', //6
  rdt: '', //2
  reality_music_competition: 'Event', //1
  record_label: 'Organization', //7
  recurring_event: 'Event', //3
  region_symbols: '', //1
  religious_biography: 'Person', //9
  religious_building: 'Place/Structure', //9
  religious_text: 'Thing', //1
  restaurant: '', //4
  river: 'Place/BodyOfWater', //16
  road: 'Place', //41
  road_small: 'Place', //14
  rocket: 'Thing', //3
  rockunit: '', //3
  roman_emperor: 'Person/Politician', //2
  royal_house: '', //1
  royalty: 'Person', //77
  rugby_biography: 'Person/Athlete', //12
  rugby_league_biography: 'Person/Athlete', //24
  rugby_league_club: 'Organization/SportsTeam', //5
  rugby_league_representative_team: 'Organization/SportsTeam', //1
  rugby_team: 'Organization/SportsTeam', //11
  russian_inhabited_locality: 'Place', //1
  russian_town: 'Place', //4
  'russian_urban-type_settlement': 'Place', //2
  saint: 'Person', //14
  scholar: 'Person', //2
  school: 'Place', //95
  school_district: 'Organization', //10
  scientist: 'Person/Scientist', //84
  scotland_council_area: 'Place', //2
  scotus_case: '', //6
  sea: 'Place/BodyOfWater', //3
  settlement: 'Place', //642
  sheep_breed: 'Thing', //1
  ship_begin: 'Thing', //84
  ship_career: 'Thing', //141
  ship_characteristics: 'Thing', //86
  ship_class_overview: 'Thing', //25
  ship_image: 'Thing', //84
  shopping_mall: 'Place', //9
  single: '', //160
  skier: 'Person/Athlete', //14
  soap_character: 'Thing/Character', //126
  software: 'Thing/Software', //25
  software_license: 'THing', //1
  song: 'CreativeWork', //30
  song_contest: 'Event', //3
  song_contest_entry: 'CreativeWork', //12
  south_african_subplace_2011: 'Place', //1
  spaceflight: 'Event', //17
  'spaceflight/dock': 'Event', //17
  'spaceflight/ip': 'Event', //19
  sport: 'Thing', //2
  sport_governing_body: 'Organization', //3
  sports_league: 'Organization', //7
  sports_season: 'Event/SportsEvent', //3
  sportsperson: 'Person', //45
  squash_player: 'Person/Athlete', //1
  stadium: 'Place/Structure', //14
  state: 'Place', //1
  state_representative: 'Person/Politician', //10
  state_senator: 'Person/Politician', //5
  station: 'Place', //40
  street: 'Place', //1
  subdivision_type: 'Thing', //1
  summit: 'Event', //2
  swimmer: 'Person/Athlete', //14
  swiss_town: 'Place', //36
  symptom: 'Thing', //2
  synthesizer: 'Thing/Product', //1
  television: 'Thing/Product', //94
  television_channel: 'Organization', //1
  television_episode: 'CreativeWork', //26
  television_season: 'CreativeWork', //18
  temple: 'Place', //2
  tennis_biography: 'Person/Athlete', //5
  tennis_event: 'Event/SportsEvent', //3
  tennis_grand_slam_events: 'Event/SportsEvent', //2
  theatre: '', //1
  thoroughbred_racehorse: 'Thing', //7
  tour_rugby: '', //1
  town_at: 'Place', //1
  train: 'Thing', //2
  treaty: 'CreativeWork', //2
  tv_channel: 'Organization', //12
  'u.s._cabinet': 'Organization', //3
  'u.s._legislation': 'Organization', //3
  'u.s._metropolitan_area': 'Place', //1
  'u.s._state': 'Place', //3
  'u.s._state_symbols': '', //4
  uk_constituency: 'Place', //1
  uk_disused_station: 'Place', //8
  uk_legislation: 'Organization', //6
  uk_place: 'Place', //22
  uk_school: 'Place', //26
  ukrainian_raion: '', //1
  unesco_world_heritage_site: 'Place', //3
  unit: '', //4
  united_states_federal_proposed_legislation: 'Thing', //1
  university: 'Organization', //44
  university_of_notre_dame_residence_hall: 'Place', //1
  v8_supercar_team: 'Organization', //3
  venue: 'Place', //6
  vg: '', //3
  vg_series: '', //4
  video_game: 'Organization', //81
  volleyball_biography: 'Person/Athlete', //1
  volleyball_player: 'Person/Athlete', //4
  waterfall: 'Place', //4
  weapon: 'Thing', //15
  website: 'Thing/Software', //5
  windmill: 'Place', //1
  worldscouting: '', //2
  wrc_driver: 'Person', //1
  wrestling_event: 'Event/SportsEvent', //8
  wrestling_promotion: '', //1
  writer: 'Person', //69
  writing_system: 'Thing', //4
  zoo: 'Place' //3
}
